import type { AnyCircuitElement } from "circuit-json"
import { PCBViewer } from "../../PCBViewer"

const circuitJson: AnyCircuitElement[] = [
  {
    type: "pcb_panel",
    pcb_panel_id: "panel",
    thickness: 1.6,
    covered_with_solder_mask: false,
    center: { x: 0, y: 0 },
    width: 228,
    height: 86,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "tenting_legend",
    text: "Via tenting = unset inherits this board, true = tented, false = exposed",
    anchor_position: { x: 0, y: 35 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.7,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_board",
    pcb_board_id: "board_A",
    subcircuit_id: "board_A",
    pcb_panel_id: "panel",
    center: { x: -57, y: -1 },
    width: 108,
    height: 66,
    material: "fr4",
    thickness: 1.6,
    num_layers: 2,
    min_via_hole_diameter: 2.5,
    min_via_pad_diameter: 5,
    default_via_tented_on_top: true,
    default_via_tented_on_bottom: false,
  },
  {
    type: "pcb_note_rect",
    pcb_note_rect_id: "outline_A",
    center: { x: -57, y: -1 },
    width: 108,
    height: 66,
    layer: "top",
    stroke_width: 0.2,
    has_stroke: true,
    is_filled: false,
    color: "#557361",
  },
  {
    type: "source_group",
    source_group_id: "source_child_A",
    subcircuit_id: "child_A",
    parent_subcircuit_id: "board_A",
    is_subcircuit: true,
  },
  {
    type: "pcb_group",
    pcb_group_id: "group_A",
    source_group_id: "source_child_A",
    subcircuit_id: "child_A",
    center: { x: -57, y: -1 },
    pcb_component_ids: [],
    anchor_alignment: "center",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_board_label",
    text: "BOARD A\nBoard defaults = top = true, bottom = false",
    anchor_position: { x: -57, y: 27 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 2.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_standalone_label",
    text: "Standalone pcb_via",
    anchor_position: { x: -57, y: 19 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 2.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_standalone_inherited_label",
    text: "top = unset\nbottom = unset\nExpect top = TENTED\nExpect bottom = EXPOSED",
    anchor_position: { x: -96, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_standalone_exposed_label",
    text: "top = false\nbottom = false\nExpect top = EXPOSED\nExpect bottom = EXPOSED",
    anchor_position: { x: -70, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_standalone_tented_label",
    text: "top = true\nbottom = true\nExpect top = TENTED\nExpect bottom = TENTED",
    anchor_position: { x: -44, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_standalone_top_override_label",
    text: "top = false\nbottom = unset\nExpect top = EXPOSED\nExpect bottom = EXPOSED",
    anchor_position: { x: -18, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "A_inherited",
    subcircuit_id: "child_A",
    x: -96,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
  },
  {
    type: "pcb_via",
    pcb_via_id: "A_exposed",
    x: -70,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    pcb_group_id: "group_A",
    tented_on_top: false,
    tented_on_bottom: false,
  },
  {
    type: "pcb_via",
    pcb_via_id: "A_tented",
    subcircuit_id: "board_A",
    x: -44,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    tented_on_top: true,
    tented_on_bottom: true,
  },
  {
    type: "pcb_via",
    pcb_via_id: "A_top_override",
    subcircuit_id: "child_A",
    x: -18,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    tented_on_top: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_route_label",
    text: "pcb_trace.route vias (same nested group)",
    anchor_position: { x: -57, y: -6 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 2.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_route_inherited_label",
    text: "top = unset\nbottom = unset\nExpect top = TENTED\nExpect bottom = EXPOSED",
    anchor_position: { x: -96, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_route_exposed_label",
    text: "top = false\nbottom = false\nExpect top = EXPOSED\nExpect bottom = EXPOSED",
    anchor_position: { x: -70, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_route_tented_label",
    text: "top = true\nbottom = true\nExpect top = TENTED\nExpect bottom = TENTED",
    anchor_position: { x: -44, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "A_route_duplicate_label",
    text: "Route top = true\nRoute bottom = true\nVia top = false\nVia bottom = false\nExpect both = EXPOSED\nNo duplicate via",
    anchor_position: { x: -18, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_A",
    pcb_group_id: "group_A",
    route: [
      { route_type: "wire", x: -101, y: -24, width: 0.7, layer: "top" },
      { route_type: "wire", x: -96, y: -24, width: 0.7, layer: "top" },
      {
        route_type: "via",
        x: -96,
        y: -24,
        from_layer: "top",
        to_layer: "bottom",
      },
      { route_type: "wire", x: -96, y: -24, width: 0.7, layer: "bottom" },
      { route_type: "wire", x: -70, y: -24, width: 0.7, layer: "bottom" },
      {
        route_type: "via",
        x: -70,
        y: -24,
        from_layer: "bottom",
        to_layer: "top",
        tented_on_top: false,
        tented_on_bottom: false,
      },
      { route_type: "wire", x: -70, y: -24, width: 0.7, layer: "top" },
      { route_type: "wire", x: -44, y: -24, width: 0.7, layer: "top" },
      {
        route_type: "via",
        x: -44,
        y: -24,
        from_layer: "top",
        to_layer: "bottom",
        tented_on_top: true,
        tented_on_bottom: true,
      },
      { route_type: "wire", x: -44, y: -24, width: 0.7, layer: "bottom" },
      { route_type: "wire", x: -18, y: -24, width: 0.7, layer: "bottom" },
      {
        route_type: "via",
        x: -18,
        y: -24,
        from_layer: "bottom",
        to_layer: "top",
        tented_on_top: true,
        tented_on_bottom: true,
      },
    ],
  },
  {
    type: "pcb_via",
    pcb_via_id: "A_duplicate",
    pcb_trace_id: "trace_A",
    x: -18,
    y: -24,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    tented_on_top: false,
    tented_on_bottom: false,
  },
  {
    type: "pcb_board",
    pcb_board_id: "board_B",
    subcircuit_id: "board_B",
    pcb_panel_id: "panel",
    center: { x: 57, y: -1 },
    width: 108,
    height: 66,
    material: "fr4",
    thickness: 1.6,
    num_layers: 2,
    min_via_hole_diameter: 2.5,
    min_via_pad_diameter: 5,
    default_via_tented_on_top: false,
    default_via_tented_on_bottom: true,
  },
  {
    type: "pcb_note_rect",
    pcb_note_rect_id: "outline_B",
    center: { x: 57, y: -1 },
    width: 108,
    height: 66,
    layer: "top",
    stroke_width: 0.2,
    has_stroke: true,
    is_filled: false,
    color: "#557361",
  },
  {
    type: "source_group",
    source_group_id: "source_child_B",
    subcircuit_id: "child_B",
    parent_subcircuit_id: "board_B",
    is_subcircuit: true,
  },
  {
    type: "pcb_group",
    pcb_group_id: "group_B",
    source_group_id: "source_child_B",
    subcircuit_id: "child_B",
    center: { x: 57, y: -1 },
    pcb_component_ids: [],
    anchor_alignment: "center",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_board_label",
    text: "BOARD B\nBoard defaults = top = false, bottom = true",
    anchor_position: { x: 57, y: 27 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 2.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_standalone_label",
    text: "Standalone pcb_via",
    anchor_position: { x: 57, y: 19 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 2.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_standalone_inherited_label",
    text: "top = unset\nbottom = unset\nExpect top = EXPOSED\nExpect bottom = TENTED",
    anchor_position: { x: 18, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_standalone_exposed_label",
    text: "top = false\nbottom = false\nExpect top = EXPOSED\nExpect bottom = EXPOSED",
    anchor_position: { x: 44, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_standalone_tented_label",
    text: "top = true\nbottom = true\nExpect top = TENTED\nExpect bottom = TENTED",
    anchor_position: { x: 70, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_standalone_top_override_label",
    text: "top = false\nbottom = unset\nExpect top = EXPOSED\nExpect bottom = TENTED",
    anchor_position: { x: 96, y: 12 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_via",
    pcb_via_id: "B_inherited",
    subcircuit_id: "child_B",
    x: 18,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
  },
  {
    type: "pcb_via",
    pcb_via_id: "B_exposed",
    x: 44,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    pcb_group_id: "group_B",
    tented_on_top: false,
    tented_on_bottom: false,
  },
  {
    type: "pcb_via",
    pcb_via_id: "B_tented",
    subcircuit_id: "board_B",
    x: 70,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    tented_on_top: true,
    tented_on_bottom: true,
  },
  {
    type: "pcb_via",
    pcb_via_id: "B_top_override",
    subcircuit_id: "child_B",
    x: 96,
    y: 5,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    tented_on_top: false,
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_route_label",
    text: "pcb_trace.route vias (same nested group)",
    anchor_position: { x: 57, y: -6 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 2.4,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_route_inherited_label",
    text: "top = unset\nbottom = unset\nExpect top = EXPOSED\nExpect bottom = TENTED",
    anchor_position: { x: 18, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_route_exposed_label",
    text: "top = false\nbottom = false\nExpect top = EXPOSED\nExpect bottom = EXPOSED",
    anchor_position: { x: 44, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_route_tented_label",
    text: "top = true\nbottom = true\nExpect top = TENTED\nExpect bottom = TENTED",
    anchor_position: { x: 70, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_note_text",
    pcb_note_text_id: "B_route_duplicate_label",
    text: "Route top = true\nRoute bottom = true\nVia top = false\nVia bottom = false\nExpect both = EXPOSED\nNo duplicate via",
    anchor_position: { x: 96, y: -12.5 },
    anchor_alignment: "center",
    font: "tscircuit2024",
    font_size: 1.5,
    layer: "top",
    color: "white",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "trace_B",
    pcb_group_id: "group_B",
    route: [
      { route_type: "wire", x: 13, y: -24, width: 0.7, layer: "top" },
      { route_type: "wire", x: 18, y: -24, width: 0.7, layer: "top" },
      {
        route_type: "via",
        x: 18,
        y: -24,
        from_layer: "top",
        to_layer: "bottom",
      },
      { route_type: "wire", x: 18, y: -24, width: 0.7, layer: "bottom" },
      { route_type: "wire", x: 44, y: -24, width: 0.7, layer: "bottom" },
      {
        route_type: "via",
        x: 44,
        y: -24,
        from_layer: "bottom",
        to_layer: "top",
        tented_on_top: false,
        tented_on_bottom: false,
      },
      { route_type: "wire", x: 44, y: -24, width: 0.7, layer: "top" },
      { route_type: "wire", x: 70, y: -24, width: 0.7, layer: "top" },
      {
        route_type: "via",
        x: 70,
        y: -24,
        from_layer: "top",
        to_layer: "bottom",
        tented_on_top: true,
        tented_on_bottom: true,
      },
      { route_type: "wire", x: 70, y: -24, width: 0.7, layer: "bottom" },
      { route_type: "wire", x: 96, y: -24, width: 0.7, layer: "bottom" },
      {
        route_type: "via",
        x: 96,
        y: -24,
        from_layer: "bottom",
        to_layer: "top",
        tented_on_top: true,
        tented_on_bottom: true,
      },
    ],
  },
  {
    type: "pcb_via",
    pcb_via_id: "B_duplicate",
    pcb_trace_id: "trace_B",
    x: 96,
    y: -24,
    layers: ["top", "bottom"],
    outer_diameter: 5,
    hole_diameter: 2.5,
    tented_on_top: false,
    tented_on_bottom: false,
  },
]

export default function BoardViaTenting() {
  return (
    <PCBViewer
      circuitJson={circuitJson}
      height={600}
      initialState={{
        is_showing_solder_mask: true,
        is_showing_pcb_notes: true,
      }}
    />
  )
}
