import type React from "react"
import { PCBViewer } from "../../PCBViewer"
import { AnyCircuitElement } from "circuit-json"

export const GroupAnchorHoverOffset: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        initialState={{ is_showing_pcb_groups: true }}
        circuitJson={
          [
            {
              type: "source_group",
              source_group_id: "source_group_0",
              name: "Grouped Section",
              is_subcircuit: undefined,
              was_automatically_named: false,
              parent_source_group_id: "source_group_1",
            },
            {
              type: "source_group",
              source_group_id: "source_group_1",
              name: undefined,
              is_subcircuit: true,
              was_automatically_named: true,
              subcircuit_id: "subcircuit_source_group_1",
            },
            {
              type: "source_port",
              source_port_id: "source_port_0",
              name: "pin1",
              pin_number: 1,
              port_hints: ["pin1", "anode", "pos", "left", "1"],
              source_component_id: "source_component_0",
              subcircuit_id: "subcircuit_source_group_1",
            },
            {
              type: "source_port",
              source_port_id: "source_port_1",
              name: "pin2",
              pin_number: 2,
              port_hints: ["pin2", "cathode", "neg", "right", "2"],
              source_component_id: "source_component_0",
              subcircuit_id: "subcircuit_source_group_1",
            },
            {
              type: "source_component",
              source_component_id: "source_component_0",
              ftype: "simple_resistor",
              name: "RG1",
              manufacturer_part_number: undefined,
              supplier_part_numbers: undefined,
              resistance: 1000,
              display_resistance: "1kΩ",
              are_pins_interchangeable: true,
              source_group_id: "source_group_0",
            },
            {
              type: "source_port",
              source_port_id: "source_port_2",
              name: "pin1",
              pin_number: 1,
              port_hints: ["pin1", "anode", "pos", "left", "1"],
              source_component_id: "source_component_1",
              subcircuit_id: "subcircuit_source_group_1",
            },
            {
              type: "source_port",
              source_port_id: "source_port_3",
              name: "pin2",
              pin_number: 2,
              port_hints: ["pin2", "cathode", "neg", "right", "2"],
              source_component_id: "source_component_1",
              subcircuit_id: "subcircuit_source_group_1",
            },
            {
              type: "source_component",
              source_component_id: "source_component_1",
              ftype: "simple_resistor",
              name: "RG2",
              manufacturer_part_number: undefined,
              supplier_part_numbers: undefined,
              resistance: 2000,
              display_resistance: "2kΩ",
              are_pins_interchangeable: true,
              source_group_id: "source_group_0",
            },
            {
              type: "source_board",
              source_board_id: "source_board_0",
              source_group_id: "source_group_1",
              title: undefined,
            },
            {
              type: "source_pin_missing_trace_warning",
              source_pin_missing_trace_warning_id:
                "source_pin_missing_trace_warning_0",
              message: "Port pin1 on RG1 is missing a trace",
              source_component_id: "source_component_0",
              source_port_id: "source_port_0",
              subcircuit_id: "subcircuit_source_group_1",
              warning_type: "source_pin_missing_trace_warning",
            },
            {
              type: "source_pin_missing_trace_warning",
              source_pin_missing_trace_warning_id:
                "source_pin_missing_trace_warning_1",
              message: "Port pin2 on RG1 is missing a trace",
              source_component_id: "source_component_0",
              source_port_id: "source_port_1",
              subcircuit_id: "subcircuit_source_group_1",
              warning_type: "source_pin_missing_trace_warning",
            },
            {
              type: "source_pin_missing_trace_warning",
              source_pin_missing_trace_warning_id:
                "source_pin_missing_trace_warning_2",
              message: "Port pin1 on RG2 is missing a trace",
              source_component_id: "source_component_1",
              source_port_id: "source_port_2",
              subcircuit_id: "subcircuit_source_group_1",
              warning_type: "source_pin_missing_trace_warning",
            },
            {
              type: "source_pin_missing_trace_warning",
              source_pin_missing_trace_warning_id:
                "source_pin_missing_trace_warning_3",
              message: "Port pin2 on RG2 is missing a trace",
              source_component_id: "source_component_1",
              source_port_id: "source_port_3",
              subcircuit_id: "subcircuit_source_group_1",
              warning_type: "source_pin_missing_trace_warning",
            },
            {
              type: "schematic_component",
              schematic_component_id: "schematic_component_0",
              center: {
                x: 0,
                y: 0,
              },
              size: {
                width: 1.1,
                height: 0.388910699999999,
              },
              source_component_id: "source_component_0",
              is_box_with_pins: true,
              symbol_name: "boxresistor_right",
              symbol_display_value: "1kΩ",
              schematic_group_id: "schematic_group_0",
            },
            {
              type: "schematic_component",
              schematic_component_id: "schematic_component_1",
              center: {
                x: 0,
                y: -1.588910699999999,
              },
              size: {
                width: 1.1,
                height: 0.388910699999999,
              },
              source_component_id: "source_component_1",
              is_box_with_pins: true,
              symbol_name: "boxresistor_right",
              symbol_display_value: "2kΩ",
              schematic_group_id: "schematic_group_0",
            },
            {
              type: "schematic_group",
              schematic_group_id: "schematic_group_0",
              is_subcircuit: undefined,
              subcircuit_id: null,
              name: "Grouped Section",
              center: {
                x: 0,
                y: 0,
              },
              width: 0,
              height: 0,
              schematic_component_ids: [],
              source_group_id: "source_group_0",
            },
            {
              type: "schematic_group",
              schematic_group_id: "schematic_group_1",
              is_subcircuit: true,
              subcircuit_id: "subcircuit_source_group_1",
              name: "unnamed_board1",
              center: {
                x: 0,
                y: 0,
              },
              width: 0,
              height: 0,
              schematic_component_ids: [],
              source_group_id: "source_group_1",
            },
            {
              type: "schematic_port",
              schematic_port_id: "schematic_port_0",
              schematic_component_id: "schematic_component_0",
              center: {
                x: -0.55,
                y: 0,
              },
              source_port_id: "source_port_0",
              facing_direction: "left",
              distance_from_component_edge: 0.4,
              side_of_component: undefined,
              pin_number: 1,
              true_ccw_index: undefined,
              display_pin_label: "anode",
              is_connected: false,
            },
            {
              type: "schematic_port",
              schematic_port_id: "schematic_port_1",
              schematic_component_id: "schematic_component_0",
              center: {
                x: 0.55,
                y: 0,
              },
              source_port_id: "source_port_1",
              facing_direction: "right",
              distance_from_component_edge: 0.4,
              side_of_component: undefined,
              pin_number: 2,
              true_ccw_index: undefined,
              display_pin_label: "cathode",
              is_connected: false,
            },
            {
              type: "schematic_port",
              schematic_port_id: "schematic_port_2",
              schematic_component_id: "schematic_component_1",
              center: {
                x: -0.55,
                y: -1.588910699999999,
              },
              source_port_id: "source_port_2",
              facing_direction: "left",
              distance_from_component_edge: 0.4,
              side_of_component: undefined,
              pin_number: 1,
              true_ccw_index: undefined,
              display_pin_label: "anode",
              is_connected: false,
            },
            {
              type: "schematic_port",
              schematic_port_id: "schematic_port_3",
              schematic_component_id: "schematic_component_1",
              center: {
                x: 0.55,
                y: -1.588910699999999,
              },
              source_port_id: "source_port_3",
              facing_direction: "right",
              distance_from_component_edge: 0.4,
              side_of_component: undefined,
              pin_number: 2,
              true_ccw_index: undefined,
              display_pin_label: "cathode",
              is_connected: false,
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_component_0",
              center: {
                x: 2,
                y: 0,
              },
              width: 2.45,
              height: 0.95,
              layer: "top",
              rotation: 0,
              source_component_id: "source_component_0",
              subcircuit_id: "subcircuit_source_group_1",
              do_not_place: false,
              obstructs_within_bounds: true,
              pcb_group_id: "pcb_group_0",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "pcb_group_0",
              positioned_relative_to_pcb_board_id: undefined,
              display_offset_x: 2,
              display_offset_y: 0,
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_component_1",
              center: {
                x: 3,
                y: 2,
              },
              width: 2.4500000000000006,
              height: 0.9500000000000002,
              layer: "top",
              rotation: 0,
              source_component_id: "source_component_1",
              subcircuit_id: "subcircuit_source_group_1",
              do_not_place: false,
              obstructs_within_bounds: true,
              pcb_group_id: "pcb_group_0",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "pcb_group_0",
              positioned_relative_to_pcb_board_id: undefined,
              display_offset_x: 3,
              display_offset_y: 2,
            },
            {
              type: "pcb_group",
              pcb_group_id: "pcb_group_0",
              is_subcircuit: undefined,
              subcircuit_id: "subcircuit_source_group_1",
              name: "Grouped Section",
              anchor_position: {
                x: 0,
                y: 0,
              },
              center: {
                x: 0,
                y: 1.5,
              },
              width: 4,
              height: 3,
              pcb_component_ids: [],
              source_group_id: "source_group_0",
              autorouter_configuration: undefined,
              anchor_alignment: "bottom_center",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: undefined,
              positioned_relative_to_pcb_board_id: "pcb_board_0",
              display_offset_x: 0,
              display_offset_y: 0,
            },
            {
              type: "pcb_board",
              pcb_board_id: "pcb_board_0",
              center: {
                x: 0,
                y: 0,
              },
              thickness: 1.4,
              num_layers: 2,
              width: 20,
              height: 20,
              outline: undefined,
              material: "fr4",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pcb_smtpad_0",
              pcb_component_id: "pcb_component_0",
              pcb_port_id: "pcb_port_0",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 0.95,
              corner_radius: undefined,
              port_hints: ["1", "left"],
              is_covered_with_solder_mask: false,
              soldermask_margin: undefined,
              x: 1.175,
              y: 0,
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_solder_paste",
              pcb_solder_paste_id: "pcb_solder_paste_0",
              layer: "top",
              shape: "rect",
              width: 0.5599999999999999,
              height: 0.6649999999999999,
              x: 1.175,
              y: 0,
              pcb_component_id: "pcb_component_0",
              pcb_smtpad_id: "pcb_smtpad_0",
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pcb_smtpad_1",
              pcb_component_id: "pcb_component_0",
              pcb_port_id: "pcb_port_1",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 0.95,
              corner_radius: undefined,
              port_hints: ["2", "right"],
              is_covered_with_solder_mask: false,
              soldermask_margin: undefined,
              x: 2.825,
              y: 0,
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_solder_paste",
              pcb_solder_paste_id: "pcb_solder_paste_1",
              layer: "top",
              shape: "rect",
              width: 0.5599999999999999,
              height: 0.6649999999999999,
              x: 2.825,
              y: 0,
              pcb_component_id: "pcb_component_0",
              pcb_smtpad_id: "pcb_smtpad_1",
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_silkscreen_path",
              pcb_silkscreen_path_id: "pcb_silkscreen_path_0",
              pcb_component_id: "pcb_component_0",
              layer: "top",
              route: [
                {
                  x: 2.825,
                  y: 0.875,
                },
                {
                  x: 0.575,
                  y: 0.875,
                },
                {
                  x: 0.575,
                  y: -0.875,
                },
                {
                  x: 2.825,
                  y: -0.875,
                },
              ],
              stroke_width: 0.1,
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_silkscreen_text",
              pcb_silkscreen_text_id: "pcb_silkscreen_text_0",
              anchor_alignment: "center",
              anchor_position: {
                x: 2,
                y: -1.375,
              },
              font: "tscircuit2024",
              font_size: 0.4,
              layer: "top",
              text: "RG1",
              ccw_rotation: 0,
              pcb_component_id: "pcb_component_0",
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pcb_smtpad_2",
              pcb_component_id: "pcb_component_1",
              pcb_port_id: "pcb_port_2",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 0.95,
              corner_radius: undefined,
              port_hints: ["1", "left"],
              is_covered_with_solder_mask: false,
              soldermask_margin: undefined,
              x: 2.175,
              y: 2,
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_solder_paste",
              pcb_solder_paste_id: "pcb_solder_paste_2",
              layer: "top",
              shape: "rect",
              width: 0.5599999999999999,
              height: 0.6649999999999999,
              x: 2.175,
              y: 2,
              pcb_component_id: "pcb_component_1",
              pcb_smtpad_id: "pcb_smtpad_2",
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pcb_smtpad_3",
              pcb_component_id: "pcb_component_1",
              pcb_port_id: "pcb_port_3",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 0.95,
              corner_radius: undefined,
              port_hints: ["2", "right"],
              is_covered_with_solder_mask: false,
              soldermask_margin: undefined,
              x: 3.825,
              y: 2,
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_solder_paste",
              pcb_solder_paste_id: "pcb_solder_paste_3",
              layer: "top",
              shape: "rect",
              width: 0.5599999999999999,
              height: 0.6649999999999999,
              x: 3.825,
              y: 2,
              pcb_component_id: "pcb_component_1",
              pcb_smtpad_id: "pcb_smtpad_3",
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_silkscreen_path",
              pcb_silkscreen_path_id: "pcb_silkscreen_path_1",
              pcb_component_id: "pcb_component_1",
              layer: "top",
              route: [
                {
                  x: 3.825,
                  y: 2.875,
                },
                {
                  x: 1.575,
                  y: 2.875,
                },
                {
                  x: 1.575,
                  y: 1.125,
                },
                {
                  x: 3.825,
                  y: 1.125,
                },
              ],
              stroke_width: 0.1,
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_silkscreen_text",
              pcb_silkscreen_text_id: "pcb_silkscreen_text_1",
              anchor_alignment: "center",
              anchor_position: {
                x: 3,
                y: 3.375,
              },
              font: "tscircuit2024",
              font_size: 0.4,
              layer: "top",
              text: "RG2",
              ccw_rotation: 0,
              pcb_component_id: "pcb_component_1",
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
            },
            {
              type: "pcb_port",
              pcb_port_id: "pcb_port_0",
              pcb_component_id: "pcb_component_0",
              layers: ["top"],
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
              x: 1.175,
              y: 0,
              source_port_id: "source_port_0",
              is_board_pinout: undefined,
            },
            {
              type: "pcb_port",
              pcb_port_id: "pcb_port_1",
              pcb_component_id: "pcb_component_0",
              layers: ["top"],
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
              x: 2.825,
              y: 0,
              source_port_id: "source_port_1",
              is_board_pinout: undefined,
            },
            {
              type: "pcb_port",
              pcb_port_id: "pcb_port_2",
              pcb_component_id: "pcb_component_1",
              layers: ["top"],
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
              x: 2.175,
              y: 2,
              source_port_id: "source_port_2",
              is_board_pinout: undefined,
            },
            {
              type: "pcb_port",
              pcb_port_id: "pcb_port_3",
              pcb_component_id: "pcb_component_1",
              layers: ["top"],
              subcircuit_id: "subcircuit_source_group_1",
              pcb_group_id: "pcb_group_0",
              x: 3.825,
              y: 2,
              source_port_id: "source_port_3",
              is_board_pinout: undefined,
            },
            {
              type: "cad_component",
              cad_component_id: "cad_component_0",
              position: {
                x: 2,
                y: 0,
                z: 0.7,
              },
              rotation: {
                x: 0,
                y: 0,
                z: 0,
              },
              pcb_component_id: "pcb_component_0",
              source_component_id: "source_component_0",
              model_stl_url: undefined,
              model_obj_url: undefined,
              model_mtl_url: undefined,
              model_gltf_url: undefined,
              model_glb_url: undefined,
              model_step_url: undefined,
              model_wrl_url: undefined,
              model_jscad: undefined,
              model_unit_to_mm_scale_factor: undefined,
              footprinter_string: "0603",
              show_as_translucent_model: undefined,
            },
            {
              type: "cad_component",
              cad_component_id: "cad_component_1",
              position: {
                x: 3,
                y: 2,
                z: 0.7,
              },
              rotation: {
                x: 0,
                y: 0,
                z: 0,
              },
              pcb_component_id: "pcb_component_1",
              source_component_id: "source_component_1",
              model_stl_url: undefined,
              model_obj_url: undefined,
              model_mtl_url: undefined,
              model_gltf_url: undefined,
              model_glb_url: undefined,
              model_step_url: undefined,
              model_wrl_url: undefined,
              model_jscad: undefined,
              model_unit_to_mm_scale_factor: undefined,
              footprinter_string: "0603",
              show_as_translucent_model: undefined,
            },
          ] as AnyCircuitElement[]
        }
      />
    </div>
  )
}

export default GroupAnchorHoverOffset
