import type { AnyCircuitElement } from "circuit-json"

export const scene = [
  {
    type: "pcb_board",
    pcb_board_id: "board",
    center: { x: 0, y: 0 },
    width: 40,
    height: 30,
    num_layers: 4,
    thickness: 1.6,
  },
  ...["a", "b"].flatMap((net, i) => [
    {
      type: "source_trace",
      source_trace_id: `source_${net}`,
      ...(net === "a" ? { name: "CLK" } : { display_name: "U1.1 to U2.2" }),
      connected_source_port_ids: [`source_port_${net}`],
      connected_source_net_ids: [`net_${net}`],
    },
    {
      type: "pcb_port",
      pcb_port_id: `port_${net}`,
      source_port_id: `source_port_${net}`,
      x: -10,
      y: i * -8,
      layers: ["top"],
    },
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: `pad_${net}`,
      pcb_port_id: `port_${net}`,
      pcb_component_id: "shared_component",
      shape: "rect",
      layer: "top",
      x: -10,
      y: i * -8,
      width: 2,
      height: 2,
    },
    ...["top", "inner1", "bottom"].map((layer, j) => ({
      type: "pcb_trace",
      pcb_trace_id: `trace_${net}_${layer}`,
      source_trace_id: `source_${net}`,
      route: [
        { route_type: "wire", x: -10 + j * 6, y: i * -8, width: 0.5, layer },
        { route_type: "wire", x: -4 + j * 6, y: i * -8, width: 0.5, layer },
      ],
    })),
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: `bottom_pad_${net}`,
      pcb_port_id: `port_${net}`,
      shape: "rect",
      layer: "bottom",
      x: 8,
      y: i * -8,
      width: 2,
      height: 2,
    },
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: `plated_${net}`,
      pcb_port_id: `port_${net}`,
      shape: "circle",
      x: 2,
      y: i * -8,
      outer_diameter: 1.5,
      hole_diameter: 0.8,
      layers: ["top", "bottom"],
    },
    {
      type: "pcb_via",
      pcb_via_id: `via_${net}`,
      source_trace_id: `source_${net}`,
      x: -4,
      y: i * -8,
      outer_diameter: 1,
      hole_diameter: 0.5,
      layers: ["top", "inner1", "inner2", "bottom"],
    },
  ]),
  ...["top", "inner1", "bottom"].map((layer) => ({
    type: "pcb_trace",
    pcb_trace_id: `cross_${layer}`,
    source_trace_id: "source_a",
    route: [
      { route_type: "wire", x: -5, y: 6, width: 2, layer },
      { route_type: "wire", x: 5, y: 6, width: 2, layer },
    ],
  })),
] as AnyCircuitElement[]
