import type React from "react"
import { PCBViewer } from "../../PCBViewer"
import type { AnyCircuitElement } from "circuit-json"

export const ComponentHoverBoundingBox: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        initialState={{
          is_showing_pcb_groups: true,
          is_showing_group_anchor_offsets: true,
        }}
        circuitJson={
          [
            {
              type: "source_component",
              source_component_id: "chip_1",
              name: "U1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_1",
              name: "R1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "capacitor_1",
              name: "C1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "led_1",
              name: "LED1",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_board",
              pcb_board_id: "pcb_board_0",
              center: { x: 0, y: 0 },
              width: 60,
              height: 40,
              thickness: 1.6,
              num_layers: 2,
              material: "fr4",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_chip_1",
              source_component_id: "chip_1",
              center: { x: -15, y: 5 },
              width: 8,
              height: 6,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_main",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_main",
              display_offset_x: "Δx: -5.00mm",
              display_offset_y: "Δy: 5.00mm",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_u1_1",
              pcb_component_id: "pcb_chip_1",
              pcb_port_id: "port_u1_1",
              shape: "rect",
              x: -18,
              y: 6.5,
              width: 0.6,
              height: 1.2,
              layer: "top",
              port_hints: ["1", "VCC"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_u1_2",
              pcb_component_id: "pcb_chip_1",
              pcb_port_id: "port_u1_2",
              shape: "rect",
              x: -16.5,
              y: 6.5,
              width: 0.6,
              height: 1.2,
              layer: "top",
              port_hints: ["2", "IN"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_u1_3",
              pcb_component_id: "pcb_chip_1",
              pcb_port_id: "port_u1_3",
              shape: "rect",
              x: -15,
              y: 6.5,
              width: 0.6,
              height: 1.2,
              layer: "top",
              port_hints: ["3", "OUT"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_u1_4",
              pcb_component_id: "pcb_chip_1",
              pcb_port_id: "port_u1_4",
              shape: "rect",
              x: -13.5,
              y: 6.5,
              width: 0.6,
              height: 1.2,
              layer: "top",
              port_hints: ["4", "EN"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_u1_5",
              pcb_component_id: "pcb_chip_1",
              pcb_port_id: "port_u1_5",
              shape: "rect",
              x: -12,
              y: 6.5,
              width: 0.6,
              height: 1.2,
              layer: "top",
              port_hints: ["5", "GND"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_u1_6",
              pcb_component_id: "pcb_chip_1",
              pcb_port_id: "port_u1_6",
              shape: "rect",
              x: -18,
              y: 3.5,
              width: 0.6,
              height: 1.2,
              layer: "top",
              port_hints: ["6"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_u1_7",
              pcb_component_id: "pcb_chip_1",
              pcb_port_id: "port_u1_7",
              shape: "rect",
              x: -12,
              y: 3.5,
              width: 0.6,
              height: 1.2,
              layer: "top",
              port_hints: ["7"],
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_1",
              source_component_id: "resistor_1",
              center: { x: -5, y: 5 },
              width: 3.2,
              height: 1.6,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_main",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_main",
              display_offset_x: "Δx: 5.00mm",
              display_offset_y: "Δy: 5.00mm",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_1",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_1",
              shape: "rect",
              x: -6.3,
              y: 5,
              width: 0.9,
              height: 1.2,
              layer: "top",
              port_hints: ["1"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_2",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_2",
              shape: "rect",
              x: -3.7,
              y: 5,
              width: 0.9,
              height: 1.2,
              layer: "top",
              port_hints: ["2"],
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_capacitor_1",
              source_component_id: "capacitor_1",
              center: { x: 5, y: -5 },
              width: 2,
              height: 3.2,
              layer: "top",
              rotation: 90,
              pcb_group_id: "group_power",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_power",
              display_offset_x: "Δx: -3.00mm",
              display_offset_y: "Δy: 0.00mm",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c1_1",
              pcb_component_id: "pcb_capacitor_1",
              pcb_port_id: "port_c1_1",
              shape: "rect",
              x: 5,
              y: -3.7,
              width: 1.8,
              height: 0.8,
              layer: "top",
              port_hints: ["1", "+"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c1_2",
              pcb_component_id: "pcb_capacitor_1",
              pcb_port_id: "port_c1_2",
              shape: "rect",
              x: 5,
              y: -6.3,
              width: 1.8,
              height: 0.8,
              layer: "top",
              port_hints: ["2", "-"],
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_led_1",
              source_component_id: "led_1",
              center: { x: 15, y: -5 },
              width: 2.5,
              height: 2.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_power",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_power",
              display_offset_x: "Δx: 7.00mm",
              display_offset_y: "Δy: 0.00mm",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_led_a",
              pcb_component_id: "pcb_led_1",
              pcb_port_id: "port_led_a",
              shape: "rect",
              x: 14.2,
              y: -5,
              width: 1,
              height: 2,
              layer: "top",
              port_hints: ["A", "anode"],
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_led_k",
              pcb_component_id: "pcb_led_1",
              pcb_port_id: "port_led_k",
              shape: "rect",
              x: 15.8,
              y: -5,
              width: 1,
              height: 2,
              layer: "top",
              port_hints: ["K", "cathode"],
            },
            {
              type: "source_group",
              source_group_id: "source_group_main",
              name: "Main Circuit",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_main",
              source_group_id: "source_group_main",
              name: "Main Circuit",
              center: { x: -10, y: 5 },
              width: 20,
              height: 10,
              anchor_position: { x: -10, y: 0 },
              anchor_alignment: "center",
              pcb_component_ids: ["pcb_chip_1", "pcb_resistor_1"],
            },
            {
              type: "source_group",
              source_group_id: "source_group_power",
              name: "Power Section",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_power",
              source_group_id: "source_group_power",
              name: "Power Section",
              center: { x: 10, y: -5 },
              width: 18,
              height: 8,
              anchor_position: { x: 8, y: -5 },
              anchor_alignment: "center_left",
              pcb_component_ids: ["pcb_capacitor_1", "pcb_led_1"],
            },
          ] as AnyCircuitElement[]
        }
      />
    </div>
  )
}

export default ComponentHoverBoundingBox
