import type React from "react"
import { PCBViewer } from "../../PCBViewer"
import type { AnyCircuitElement } from "circuit-json"

export const GroupAnchorToAnchorOffset: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        initialState={{
          is_showing_pcb_groups: true,
          is_showing_group_anchor_offsets: true,
        }}
        circuitJson={
          [
            {
              type: "source_component",
              source_component_id: "r1",
              name: "R1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "r2",
              name: "R2",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "r3",
              name: "R3",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "r4",
              name: "R4",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "c1",
              name: "C1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "c2",
              name: "C2",
              supplier_part_numbers: {},
            },

            {
              type: "pcb_board",
              pcb_board_id: "board_0",
              center: { x: 0, y: 0 },
              width: 50,
              height: 40,
              thickness: 1.6,
              num_layers: 2,
              material: "fr4",
            },

            // === ROOT GROUP (anchor at origin) ===
            {
              type: "pcb_component",
              pcb_component_id: "pcb_r1",
              source_component_id: "r1",
              center: { x: -2, y: 0 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_root",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_1",
              pcb_component_id: "pcb_r1",
              pcb_port_id: "port_r1_1",
              shape: "rect",
              x: -3.25,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_2",
              pcb_component_id: "pcb_r1",
              pcb_port_id: "port_r1_2",
              shape: "rect",
              x: -0.75,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_r2",
              source_component_id: "r2",
              center: { x: 2, y: 0 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_root",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_1",
              pcb_component_id: "pcb_r2",
              pcb_port_id: "port_r2_1",
              shape: "rect",
              x: 0.75,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_2",
              pcb_component_id: "pcb_r2",
              pcb_port_id: "port_r2_2",
              shape: "rect",
              x: 3.25,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "src_group_root",
              name: "Root Group",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_root",
              source_group_id: "src_group_root",
              name: "Root Group",
              center: { x: 0, y: 0 },
              width: 10,
              height: 4,
              anchor_position: { x: 0, y: 0 },
              anchor_alignment: "center",
              pcb_component_ids: ["pcb_r1", "pcb_r2"],
            },

            // === CHILD GROUP A (positioned 15mm right from root anchor) ===
            {
              type: "pcb_component",
              pcb_component_id: "pcb_r3",
              source_component_id: "r3",
              center: { x: 13, y: 0 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_a",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_1",
              pcb_component_id: "pcb_r3",
              pcb_port_id: "port_r3_1",
              shape: "rect",
              x: 11.75,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_2",
              pcb_component_id: "pcb_r3",
              pcb_port_id: "port_r3_2",
              shape: "rect",
              x: 14.25,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_r4",
              source_component_id: "r4",
              center: { x: 17, y: 0 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_a",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r4_1",
              pcb_component_id: "pcb_r4",
              pcb_port_id: "port_r4_1",
              shape: "rect",
              x: 15.75,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r4_2",
              pcb_component_id: "pcb_r4",
              pcb_port_id: "port_r4_2",
              shape: "rect",
              x: 18.25,
              y: 0,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "src_group_a",
              name: "Child Group A",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_a",
              source_group_id: "src_group_a",
              name: "Child Group A",
              center: { x: 15, y: 0 },
              width: 10,
              height: 4,
              anchor_position: { x: 15, y: 0 },
              anchor_alignment: "center",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_root",
              display_offset_x: "15.00mm",
              display_offset_y: "0.00mm",
              pcb_component_ids: ["pcb_r3", "pcb_r4"],
            },

            // === CHILD GROUP B (positioned 10mm down, 8mm right from root anchor) ===
            {
              type: "pcb_component",
              pcb_component_id: "pcb_c1",
              source_component_id: "c1",
              center: { x: 6, y: -10 },
              width: 2.5,
              height: 2.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_b",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c1_1",
              pcb_component_id: "pcb_c1",
              pcb_port_id: "port_c1_1",
              shape: "rect",
              x: 5,
              y: -10,
              width: 0.6,
              height: 1.2,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c1_2",
              pcb_component_id: "pcb_c1",
              pcb_port_id: "port_c1_2",
              shape: "rect",
              x: 7,
              y: -10,
              width: 0.6,
              height: 1.2,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_c2",
              source_component_id: "c2",
              center: { x: 10, y: -10 },
              width: 2.5,
              height: 2.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_b",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c2_1",
              pcb_component_id: "pcb_c2",
              pcb_port_id: "port_c2_1",
              shape: "rect",
              x: 9,
              y: -10,
              width: 0.6,
              height: 1.2,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c2_2",
              pcb_component_id: "pcb_c2",
              pcb_port_id: "port_c2_2",
              shape: "rect",
              x: 11,
              y: -10,
              width: 0.6,
              height: 1.2,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "src_group_b",
              name: "Child Group B",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_b",
              source_group_id: "src_group_b",
              name: "Child Group B",
              center: { x: 8, y: -10 },
              width: 8,
              height: 5,
              anchor_position: { x: 8, y: -10 },
              anchor_alignment: "center",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_root",
              display_offset_x: "8.00mm",
              display_offset_y: "-10.00mm",
              pcb_component_ids: ["pcb_c1", "pcb_c2"],
            },
          ] as AnyCircuitElement[]
        }
      />
    </div>
  )
}

export default GroupAnchorToAnchorOffset
