import { PCBViewer } from "../../PCBViewer"

const SoldermaskMarginComprehensiveFixture = () => {
  // Layout configuration - centered around x: 0
  const colSpacing = 10 // spacing between columns
  const numCols = 16
  const totalWidth = (numCols - 1) * colSpacing
  const startX = -totalWidth / 2 // center the columns

  // Column X positions (centered around 0)
  const col = {
    // SMT Pads (columns 1-6)
    rotatedRect: startX + 0 * colSpacing,
    polygon: startX + 1 * colSpacing,
    pill: startX + 2 * colSpacing,
    rotatedPill: startX + 3 * colSpacing,
    circlePad: startX + 4 * colSpacing,
    rectPad: startX + 5 * colSpacing,
    // Plated Holes (columns 7-13)
    circlePlatedHole: startX + 6 * colSpacing,
    ovalPlatedHole: startX + 7 * colSpacing,
    pillPlatedHole: startX + 8 * colSpacing,
    circRectPTH: startX + 9 * colSpacing,
    pillRectPTH: startX + 10 * colSpacing,
    rotPillRectPTH: startX + 11 * colSpacing,
    polyPadPTH: startX + 12 * colSpacing,
    // Non-plated Holes (columns 14-16)
    circleHole: startX + 13 * colSpacing,
    ovalHole: startX + 14 * colSpacing,
    pillHole: startX + 15 * colSpacing,
  }

  // Row Y positions (centered around 0)
  const row = {
    fullyCovered: 12,
    positiveMargin: 4,
    negativeMargin: -4,
    default: -12,
  }

  // Helper for polygon pad outline (hexagon centered at origin)
  const polyPadOutline = [
    { x: -1, y: -1.5 },
    { x: 1, y: -1.5 },
    { x: 1.5, y: 0 },
    { x: 1, y: 1.5 },
    { x: -1, y: 1.5 },
    { x: -1.5, y: 0 },
  ]

  const circuitJson = [
    {
      type: "pcb_board",
      pcb_board_id: "board_test",
      center: { x: 0, y: 0 },
      width: 180,
      height: 45,
      thickness: 1.6,
      num_layers: 2,
      material: "fr4",
    } as any,
    {
      type: "pcb_component",
      pcb_component_id: "dummy_component",
      center: { x: 0, y: 0 },
      width: 180,
      height: 45,
      rotation: 0,
      layer: "top",
      source_component_id: "dummy",
      obstructs_within_bounds: false,
    } as any,

    // =====================================================
    // Row 1: Fully covered elements (is_covered_with_solder_mask = true)
    // =====================================================

    // Column 1: Rotated Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_fully_covered_rotated_rect",
      shape: "rotated_rect",
      x: col.rotatedRect,
      y: row.fullyCovered,
      width: 2,
      height: 1,
      ccw_rotation: 30,
      layer: "top",
      is_covered_with_solder_mask: true,
    } as any,
    // Column 2: Polygon SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_fully_covered_polygon",
      shape: "polygon",
      layer: "top",
      points: [
        { x: col.polygon - 1, y: row.fullyCovered - 1 },
        { x: col.polygon + 1, y: row.fullyCovered - 1 },
        { x: col.polygon + 2, y: row.fullyCovered + 1 },
        { x: col.polygon + 1, y: row.fullyCovered + 3 },
        { x: col.polygon - 1, y: row.fullyCovered + 3 },
        { x: col.polygon - 2, y: row.fullyCovered + 1 },
      ],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 3: Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_fully_covered_pill",
      shape: "pill",
      x: col.pill,
      y: row.fullyCovered,
      width: 3,
      height: 1,
      radius: 0.5,
      layer: "top",
      is_covered_with_solder_mask: true,
    } as any,
    // Column 4: Rotated Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_fully_covered_rotated_pill",
      shape: "rotated_pill",
      x: col.rotatedPill,
      y: row.fullyCovered,
      width: 3,
      height: 1,
      radius: 0.5,
      ccw_rotation: 30,
      layer: "top",
      is_covered_with_solder_mask: true,
    } as any,
    // Column 5: Circle SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_fully_covered_circle",
      shape: "circle",
      x: col.circlePad,
      y: row.fullyCovered,
      radius: 1,
      layer: "top",
      is_covered_with_solder_mask: true,
    } as any,
    // Column 6: Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_fully_covered_rect",
      shape: "rect",
      x: col.rectPad,
      y: row.fullyCovered,
      width: 2,
      height: 2,
      layer: "top",
      is_covered_with_solder_mask: true,
    } as any,
    // Column 7: Circle Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_fully_covered_circle",
      shape: "circle",
      x: col.circlePlatedHole,
      y: row.fullyCovered,
      hole_diameter: 1,
      outer_diameter: 2,
      layers: ["top", "bottom"],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 8: Oval Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_fully_covered_oval",
      shape: "oval",
      x: col.ovalPlatedHole,
      y: row.fullyCovered,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 9: Pill Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_fully_covered_pill",
      shape: "pill",
      x: col.pillPlatedHole,
      y: row.fullyCovered,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 10: Circular Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_fully_covered_circ_rect",
      shape: "circular_hole_with_rect_pad",
      x: col.circRectPTH,
      y: row.fullyCovered,
      hole_shape: "circle",
      hole_diameter: 1,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 11: Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_fully_covered_pill_rect",
      shape: "pill_hole_with_rect_pad",
      x: col.pillRectPTH,
      y: row.fullyCovered,
      hole_shape: "pill",
      hole_width: 2,
      hole_height: 0.8,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 12: Rotated Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_fully_covered_rot_pill_rect",
      shape: "rotated_pill_hole_with_rect_pad",
      x: col.rotPillRectPTH,
      y: row.fullyCovered,
      hole_shape: "rotated_pill",
      hole_width: 2,
      hole_height: 0.8,
      hole_ccw_rotation: 45,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      rect_ccw_rotation: 30,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 13: Hole with Polygon Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_fully_covered_poly_pad",
      shape: "hole_with_polygon_pad",
      x: col.polyPadPTH,
      y: row.fullyCovered,
      hole_shape: "circle",
      hole_diameter: 0.8,
      hole_offset_x: 0,
      hole_offset_y: 0,
      pad_outline: polyPadOutline,
      layers: ["top", "bottom"],
      is_covered_with_solder_mask: true,
    } as any,
    // Column 14: Circle Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_fully_covered_circle",
      hole_shape: "circle",
      x: col.circleHole,
      y: row.fullyCovered,
      hole_diameter: 1,
      is_covered_with_solder_mask: true,
    } as any,
    // Column 15: Oval Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_fully_covered_oval",
      hole_shape: "oval",
      x: col.ovalHole,
      y: row.fullyCovered,
      hole_width: 2,
      hole_height: 1,
      is_covered_with_solder_mask: true,
    } as any,
    // Column 16: Pill Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_fully_covered_pill",
      hole_shape: "pill",
      x: col.pillHole,
      y: row.fullyCovered,
      hole_width: 2,
      hole_height: 1,
      is_covered_with_solder_mask: true,
    } as any,

    // =====================================================
    // Row 2: Positive margin (soldermask_margin = 0.5)
    // =====================================================

    // Column 1: Rotated Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_positive_margin_rotated_rect",
      shape: "rotated_rect",
      x: col.rotatedRect,
      y: row.positiveMargin,
      width: 2,
      height: 1,
      ccw_rotation: 30,
      layer: "top",
      soldermask_margin: 0.5,
    } as any,
    // Column 2: Polygon SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_positive_margin_polygon",
      shape: "polygon",
      layer: "top",
      points: [
        { x: col.polygon - 1, y: row.positiveMargin - 1 },
        { x: col.polygon + 1, y: row.positiveMargin - 1 },
        { x: col.polygon + 2, y: row.positiveMargin + 1 },
        { x: col.polygon + 1, y: row.positiveMargin + 3 },
        { x: col.polygon - 1, y: row.positiveMargin + 3 },
        { x: col.polygon - 2, y: row.positiveMargin + 1 },
      ],
      soldermask_margin: 0.5,
    } as any,
    // Column 3: Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_positive_margin_pill",
      shape: "pill",
      x: col.pill,
      y: row.positiveMargin,
      width: 3,
      height: 1,
      radius: 0.5,
      layer: "top",
      soldermask_margin: 0.5,
    } as any,
    // Column 4: Rotated Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_positive_margin_rotated_pill",
      shape: "rotated_pill",
      x: col.rotatedPill,
      y: row.positiveMargin,
      width: 3,
      height: 1,
      radius: 0.5,
      ccw_rotation: 30,
      layer: "top",
      soldermask_margin: 0.5,
    } as any,
    // Column 5: Circle SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_positive_margin_circle",
      shape: "circle",
      x: col.circlePad,
      y: row.positiveMargin,
      radius: 1,
      layer: "top",
      soldermask_margin: 0.5,
    } as any,
    // Column 6: Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_positive_margin_rect",
      shape: "rect",
      x: col.rectPad,
      y: row.positiveMargin,
      width: 2,
      height: 2,
      layer: "top",
      soldermask_margin: 0.5,
    } as any,
    // Column 7: Circle Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_positive_margin_circle",
      shape: "circle",
      x: col.circlePlatedHole,
      y: row.positiveMargin,
      hole_diameter: 1,
      outer_diameter: 2,
      layers: ["top", "bottom"],
      soldermask_margin: 0.5,
    } as any,
    // Column 8: Oval Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_positive_margin_oval",
      shape: "oval",
      x: col.ovalPlatedHole,
      y: row.positiveMargin,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
      soldermask_margin: 0.5,
    } as any,
    // Column 9: Pill Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_positive_margin_pill",
      shape: "pill",
      x: col.pillPlatedHole,
      y: row.positiveMargin,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
      soldermask_margin: 0.5,
    } as any,
    // Column 10: Circular Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_positive_margin_circ_rect",
      shape: "circular_hole_with_rect_pad",
      x: col.circRectPTH,
      y: row.positiveMargin,
      hole_shape: "circle",
      hole_diameter: 1,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      soldermask_margin: 0.5,
    } as any,
    // Column 11: Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_positive_margin_pill_rect",
      shape: "pill_hole_with_rect_pad",
      x: col.pillRectPTH,
      y: row.positiveMargin,
      hole_shape: "pill",
      hole_width: 2,
      hole_height: 0.8,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      soldermask_margin: 0.5,
    } as any,
    // Column 12: Rotated Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_positive_margin_rot_pill_rect",
      shape: "rotated_pill_hole_with_rect_pad",
      x: col.rotPillRectPTH,
      y: row.positiveMargin,
      hole_shape: "rotated_pill",
      hole_width: 2,
      hole_height: 0.8,
      hole_ccw_rotation: 45,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      rect_ccw_rotation: 30,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      soldermask_margin: 0.5,
    } as any,
    // Column 13: Hole with Polygon Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_positive_margin_poly_pad",
      shape: "hole_with_polygon_pad",
      x: col.polyPadPTH,
      y: row.positiveMargin,
      hole_shape: "circle",
      hole_diameter: 0.8,
      hole_offset_x: 0,
      hole_offset_y: 0,
      pad_outline: polyPadOutline,
      layers: ["top", "bottom"],
      soldermask_margin: 0.5,
    } as any,
    // Column 14: Circle Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_positive_margin_circle",
      hole_shape: "circle",
      x: col.circleHole,
      y: row.positiveMargin,
      hole_diameter: 1,
      soldermask_margin: 0.5,
    } as any,
    // Column 15: Oval Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_positive_margin_oval",
      hole_shape: "oval",
      x: col.ovalHole,
      y: row.positiveMargin,
      hole_width: 2,
      hole_height: 1,
      soldermask_margin: 0.5,
    } as any,
    // Column 16: Pill Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_positive_margin_pill",
      hole_shape: "pill",
      x: col.pillHole,
      y: row.positiveMargin,
      hole_width: 2,
      hole_height: 1,
      soldermask_margin: 0.5,
    } as any,

    // =====================================================
    // Row 3: Negative margin (soldermask_margin = -0.3)
    // =====================================================

    // Column 1: Rotated Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_negative_margin_rotated_rect",
      shape: "rotated_rect",
      x: col.rotatedRect,
      y: row.negativeMargin,
      width: 2,
      height: 1,
      ccw_rotation: 30,
      layer: "top",
      soldermask_margin: -0.3,
    } as any,
    // Column 2: Polygon SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_negative_margin_polygon",
      shape: "polygon",
      layer: "top",
      points: [
        { x: col.polygon - 1, y: row.negativeMargin - 1 },
        { x: col.polygon + 1, y: row.negativeMargin - 1 },
        { x: col.polygon + 2, y: row.negativeMargin + 1 },
        { x: col.polygon + 1, y: row.negativeMargin + 3 },
        { x: col.polygon - 1, y: row.negativeMargin + 3 },
        { x: col.polygon - 2, y: row.negativeMargin + 1 },
      ],
      soldermask_margin: -0.3,
    } as any,
    // Column 3: Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_negative_margin_pill",
      shape: "pill",
      x: col.pill,
      y: row.negativeMargin,
      width: 3,
      height: 1,
      radius: 0.5,
      layer: "top",
      soldermask_margin: -0.3,
    } as any,
    // Column 4: Rotated Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_negative_margin_rotated_pill",
      shape: "rotated_pill",
      x: col.rotatedPill,
      y: row.negativeMargin,
      width: 3,
      height: 1,
      radius: 0.5,
      ccw_rotation: 30,
      layer: "top",
      soldermask_margin: -0.3,
    } as any,
    // Column 5: Circle SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_negative_margin_circle",
      shape: "circle",
      x: col.circlePad,
      y: row.negativeMargin,
      radius: 1,
      layer: "top",
      soldermask_margin: -0.3,
    } as any,
    // Column 6: Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_negative_margin_rect",
      shape: "rect",
      x: col.rectPad,
      y: row.negativeMargin,
      width: 2,
      height: 2,
      layer: "top",
      soldermask_margin: -0.3,
    } as any,
    // Column 7: Circle Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_negative_margin_circle",
      shape: "circle",
      x: col.circlePlatedHole,
      y: row.negativeMargin,
      hole_diameter: 1,
      outer_diameter: 2,
      layers: ["top", "bottom"],
      soldermask_margin: -0.3,
    } as any,
    // Column 8: Oval Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_negative_margin_oval",
      shape: "oval",
      x: col.ovalPlatedHole,
      y: row.negativeMargin,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
      soldermask_margin: -0.3,
    } as any,
    // Column 9: Pill Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_negative_margin_pill",
      shape: "pill",
      x: col.pillPlatedHole,
      y: row.negativeMargin,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
      soldermask_margin: -0.3,
    } as any,
    // Column 10: Circular Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_negative_margin_circ_rect",
      shape: "circular_hole_with_rect_pad",
      x: col.circRectPTH,
      y: row.negativeMargin,
      hole_shape: "circle",
      hole_diameter: 1,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      soldermask_margin: -0.3,
    } as any,
    // Column 11: Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_negative_margin_pill_rect",
      shape: "pill_hole_with_rect_pad",
      x: col.pillRectPTH,
      y: row.negativeMargin,
      hole_shape: "pill",
      hole_width: 2,
      hole_height: 0.8,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      soldermask_margin: -0.3,
    } as any,
    // Column 12: Rotated Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_negative_margin_rot_pill_rect",
      shape: "rotated_pill_hole_with_rect_pad",
      x: col.rotPillRectPTH,
      y: row.negativeMargin,
      hole_shape: "rotated_pill",
      hole_width: 2,
      hole_height: 0.8,
      hole_ccw_rotation: 45,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      rect_ccw_rotation: 30,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
      soldermask_margin: -0.3,
    } as any,
    // Column 13: Hole with Polygon Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_negative_margin_poly_pad",
      shape: "hole_with_polygon_pad",
      x: col.polyPadPTH,
      y: row.negativeMargin,
      hole_shape: "circle",
      hole_diameter: 0.8,
      hole_offset_x: 0,
      hole_offset_y: 0,
      pad_outline: polyPadOutline,
      layers: ["top", "bottom"],
      soldermask_margin: -0.3,
    } as any,
    // Column 14: Circle Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_negative_margin_circle",
      hole_shape: "circle",
      x: col.circleHole,
      y: row.negativeMargin,
      hole_diameter: 1,
      soldermask_margin: -0.3,
    } as any,
    // Column 15: Oval Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_negative_margin_oval",
      hole_shape: "oval",
      x: col.ovalHole,
      y: row.negativeMargin,
      hole_width: 2,
      hole_height: 1,
      soldermask_margin: -0.3,
    } as any,
    // Column 16: Pill Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_negative_margin_pill",
      hole_shape: "pill",
      x: col.pillHole,
      y: row.negativeMargin,
      hole_width: 2,
      hole_height: 1,
      soldermask_margin: -0.3,
    } as any,

    // =====================================================
    // Row 4: Default behavior (no margin specified)
    // =====================================================

    // Column 1: Rotated Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_default_rotated_rect",
      shape: "rotated_rect",
      x: col.rotatedRect,
      y: row.default,
      width: 2,
      height: 1,
      ccw_rotation: 30,
      layer: "top",
    } as any,
    // Column 2: Polygon SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_default_polygon",
      shape: "polygon",
      layer: "top",
      points: [
        { x: col.polygon - 1, y: row.default - 1 },
        { x: col.polygon + 1, y: row.default - 1 },
        { x: col.polygon + 2, y: row.default + 1 },
        { x: col.polygon + 1, y: row.default + 3 },
        { x: col.polygon - 1, y: row.default + 3 },
        { x: col.polygon - 2, y: row.default + 1 },
      ],
    } as any,
    // Column 3: Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_default_pill",
      shape: "pill",
      x: col.pill,
      y: row.default,
      width: 3,
      height: 1,
      radius: 0.5,
      layer: "top",
    } as any,
    // Column 4: Rotated Pill SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_default_rotated_pill",
      shape: "rotated_pill",
      x: col.rotatedPill,
      y: row.default,
      width: 3,
      height: 1,
      radius: 0.5,
      ccw_rotation: 30,
      layer: "top",
    } as any,
    // Column 5: Circle SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_default_circle",
      shape: "circle",
      x: col.circlePad,
      y: row.default,
      radius: 1,
      layer: "top",
    } as any,
    // Column 6: Rect SMT Pad
    {
      type: "pcb_smtpad",
      pcb_smtpad_id: "pad_default_rect",
      shape: "rect",
      x: col.rectPad,
      y: row.default,
      width: 2,
      height: 2,
      layer: "top",
    } as any,
    // Column 7: Circle Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_default_circle",
      shape: "circle",
      x: col.circlePlatedHole,
      y: row.default,
      hole_diameter: 1,
      outer_diameter: 2,
      layers: ["top", "bottom"],
    } as any,
    // Column 8: Oval Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_default_oval",
      shape: "oval",
      x: col.ovalPlatedHole,
      y: row.default,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
    } as any,
    // Column 9: Pill Plated Hole
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_default_pill",
      shape: "pill",
      x: col.pillPlatedHole,
      y: row.default,
      outer_width: 3,
      outer_height: 1.5,
      hole_width: 2,
      hole_height: 0.8,
      ccw_rotation: 0,
      layers: ["top", "bottom"],
    } as any,
    // Column 10: Circular Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_default_circ_rect",
      shape: "circular_hole_with_rect_pad",
      x: col.circRectPTH,
      y: row.default,
      hole_shape: "circle",
      hole_diameter: 1,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
    } as any,
    // Column 11: Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_default_pill_rect",
      shape: "pill_hole_with_rect_pad",
      x: col.pillRectPTH,
      y: row.default,
      hole_shape: "pill",
      hole_width: 2,
      hole_height: 0.8,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
    } as any,
    // Column 12: Rotated Pill Hole with Rect Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_default_rot_pill_rect",
      shape: "rotated_pill_hole_with_rect_pad",
      x: col.rotPillRectPTH,
      y: row.default,
      hole_shape: "rotated_pill",
      hole_width: 2,
      hole_height: 0.8,
      hole_ccw_rotation: 45,
      pad_shape: "rect",
      rect_pad_width: 3,
      rect_pad_height: 2,
      rect_ccw_rotation: 30,
      hole_offset_x: 0,
      hole_offset_y: 0,
      layers: ["top", "bottom"],
    } as any,
    // Column 13: Hole with Polygon Pad
    {
      type: "pcb_plated_hole",
      pcb_plated_hole_id: "hole_default_poly_pad",
      shape: "hole_with_polygon_pad",
      x: col.polyPadPTH,
      y: row.default,
      hole_shape: "circle",
      hole_diameter: 0.8,
      hole_offset_x: 0,
      hole_offset_y: 0,
      pad_outline: polyPadOutline,
      layers: ["top", "bottom"],
    } as any,
    // Column 14: Circle Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_default_circle",
      hole_shape: "circle",
      x: col.circleHole,
      y: row.default,
      hole_diameter: 1,
    } as any,
    // Column 15: Oval Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_default_oval",
      hole_shape: "oval",
      x: col.ovalHole,
      y: row.default,
      hole_width: 2,
      hole_height: 1,
    } as any,
    // Column 16: Pill Hole
    {
      type: "pcb_hole",
      pcb_hole_id: "np_hole_default_pill",
      hole_shape: "pill",
      x: col.pillHole,
      y: row.default,
      hole_width: 2,
      hole_height: 1,
    } as any,

    // =====================================================
    // Row labels (left side)
    // =====================================================
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_fully_covered",
      pcb_component_id: "dummy_component",
      text: "FULLY COVERED",
      layer: "top",
      anchor_position: { x: -90, y: row.fullyCovered },
      anchor_alignment: "center_left",
      font_size: 1,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_positive_margin",
      pcb_component_id: "dummy_component",
      text: "POSITIVE MARGIN",
      layer: "top",
      anchor_position: { x: -90, y: row.positiveMargin },
      anchor_alignment: "center_left",
      font_size: 1,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_negative_margin",
      pcb_component_id: "dummy_component",
      text: "NEGATIVE MARGIN",
      layer: "top",
      anchor_position: { x: -90, y: row.negativeMargin },
      anchor_alignment: "center_left",
      font_size: 1,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_default",
      pcb_component_id: "dummy_component",
      text: "DEFAULT",
      layer: "top",
      anchor_position: { x: -90, y: row.default },
      anchor_alignment: "center_left",
      font_size: 1,
      font: "tscircuit2024",
    } as any,

    // =====================================================
    // Row separators
    // =====================================================
    {
      type: "pcb_silkscreen_path",
      pcb_silkscreen_path_id: "separator_1",
      layer: "top",
      stroke_width: 0.1,
      route: [
        { x: -90, y: 8 },
        { x: 90, y: 8 },
      ],
    } as any,
    {
      type: "pcb_silkscreen_path",
      pcb_silkscreen_path_id: "separator_2",
      layer: "top",
      stroke_width: 0.1,
      route: [
        { x: -90, y: 0 },
        { x: 90, y: 0 },
      ],
    } as any,
    {
      type: "pcb_silkscreen_path",
      pcb_silkscreen_path_id: "separator_3",
      layer: "top",
      stroke_width: 0.1,
      route: [
        { x: -90, y: -8 },
        { x: 90, y: -8 },
      ],
    } as any,

    // =====================================================
    // Column labels (top)
    // =====================================================
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_rotated_rect",
      pcb_component_id: "dummy_component",
      text: "ROT RECT",
      layer: "top",
      anchor_position: { x: col.rotatedRect, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_polygon",
      pcb_component_id: "dummy_component",
      text: "POLYGON",
      layer: "top",
      anchor_position: { x: col.polygon, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_pill",
      pcb_component_id: "dummy_component",
      text: "PILL",
      layer: "top",
      anchor_position: { x: col.pill, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_rotated_pill",
      pcb_component_id: "dummy_component",
      text: "ROT PILL",
      layer: "top",
      anchor_position: { x: col.rotatedPill, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_circle_pad",
      pcb_component_id: "dummy_component",
      text: "CIRCLE",
      layer: "top",
      anchor_position: { x: col.circlePad, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_rect_pad",
      pcb_component_id: "dummy_component",
      text: "RECT",
      layer: "top",
      anchor_position: { x: col.rectPad, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_circle_plated",
      pcb_component_id: "dummy_component",
      text: "CIRC PTH",
      layer: "top",
      anchor_position: { x: col.circlePlatedHole, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_oval_plated",
      pcb_component_id: "dummy_component",
      text: "OVAL PTH",
      layer: "top",
      anchor_position: { x: col.ovalPlatedHole, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_pill_plated",
      pcb_component_id: "dummy_component",
      text: "PILL PTH",
      layer: "top",
      anchor_position: { x: col.pillPlatedHole, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_circ_rect",
      pcb_component_id: "dummy_component",
      text: "C+RECT",
      layer: "top",
      anchor_position: { x: col.circRectPTH, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_pill_rect",
      pcb_component_id: "dummy_component",
      text: "P+RECT",
      layer: "top",
      anchor_position: { x: col.pillRectPTH, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_rot_pill_rect",
      pcb_component_id: "dummy_component",
      text: "RP+RECT",
      layer: "top",
      anchor_position: { x: col.rotPillRectPTH, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_poly_pad",
      pcb_component_id: "dummy_component",
      text: "POLY PAD",
      layer: "top",
      anchor_position: { x: col.polyPadPTH, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_circle_hole",
      pcb_component_id: "dummy_component",
      text: "CIRC HOLE",
      layer: "top",
      anchor_position: { x: col.circleHole, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_oval_hole",
      pcb_component_id: "dummy_component",
      text: "OVAL HOLE",
      layer: "top",
      anchor_position: { x: col.ovalHole, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
    {
      type: "pcb_silkscreen_text",
      pcb_silkscreen_text_id: "label_col_pill_hole",
      pcb_component_id: "dummy_component",
      text: "PILL HOLE",
      layer: "top",
      anchor_position: { x: col.pillHole, y: 18 },
      anchor_alignment: "center",
      font_size: 0.8,
      font: "tscircuit2024",
    } as any,
  ]

  return (
    <div style={{ backgroundColor: "black", width: "100%", height: "600px" }}>
      <PCBViewer circuitJson={circuitJson} />
    </div>
  )
}

export default SoldermaskMarginComprehensiveFixture
