import type React from "react"
import { PCBViewer } from "../PCBViewer"
import { AnyCircuitElement } from "circuit-json"

export const GroupToGroupAndBoardAnchor: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        initialState={{
          is_showing_pcb_groups: true,
          is_showing_group_anchor_offsets: true,
        }}
        circuitJson={
          [
            {
              type: "source_component",
              source_component_id: "resistor_1",
              name: "R1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_2",
              name: "R2",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_3",
              name: "R3",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_4",
              name: "R4",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_5",
              name: "R5",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_6",
              name: "R6",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_board",
              pcb_board_id: "pcb_board_0",
              center: { x: 0, y: 0 },
              width: 40,
              height: 30,
              thickness: 1.6,
              num_layers: 4,
              material: "fr4",
            },
            // Base Group 1 - Positioned away from board center to show distinction
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_1",
              source_component_id: "resistor_1",
              center: { x: -8.5, y: -7 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_1",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_1",
              shape: "rect",
              x: -9.75,
              y: -7,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_2",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_2",
              shape: "rect",
              x: -7.25,
              y: -7,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_2",
              source_component_id: "resistor_2",
              center: { x: -4.5, y: -9 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_1",
              pcb_component_id: "pcb_resistor_2",
              pcb_port_id: "port_r2_1",
              shape: "rect",
              x: -5.75,
              y: -9,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_2",
              pcb_component_id: "pcb_resistor_2",
              pcb_port_id: "port_r2_2",
              shape: "rect",
              x: -3.25,
              y: -9,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_1",
              name: "Base Group",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_1",
              source_group_id: "source_group_1",
              name: "Base Group",
              center: { x: -6, y: -8 },
              width: 8,
              height: 4,
              anchor_position: { x: -6, y: -8 },
              anchor_alignment: "center",
              pcb_component_ids: ["pcb_resistor_1", "pcb_resistor_2"],
            },
            // Group 2 - Positioned relative to Group 1's anchor (clearly offset from Group 1)
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_3",
              source_component_id: "resistor_3",
              center: { x: 4.5, y: -8 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_1",
              pcb_component_id: "pcb_resistor_3",
              pcb_port_id: "port_r3_1",
              shape: "rect",
              x: 3.25,
              y: -8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_2",
              pcb_component_id: "pcb_resistor_3",
              pcb_port_id: "port_r3_2",
              shape: "rect",
              x: 5.75,
              y: -8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_4",
              source_component_id: "resistor_4",
              center: { x: 7.5, y: -8 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r4_1",
              pcb_component_id: "pcb_resistor_4",
              pcb_port_id: "port_r4_1",
              shape: "rect",
              x: 6.25,
              y: -8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r4_2",
              pcb_component_id: "pcb_resistor_4",
              pcb_port_id: "port_r4_2",
              shape: "rect",
              x: 8.75,
              y: -8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_2",
              name: "Group Relative to Group",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_2",
              source_group_id: "source_group_2",
              name: "Group Relative to Group",
              center: { x: 6, y: -8 },
              width: 7,
              height: 3,
              anchor_position: { x: 6, y: -8 },
              anchor_alignment: "center",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_1",
              display_offset_x: "Group Δx: 12.00mm",
              display_offset_y: "Group Δy: 0.00mm",
              pcb_component_ids: ["pcb_resistor_3", "pcb_resistor_4"],
            },
            // Group 3 - Positioned relative to Board center (0, 0) - clearly different from Group 1
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_5",
              source_component_id: "resistor_5",
              center: { x: -8.5, y: 8 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r5_1",
              pcb_component_id: "pcb_resistor_5",
              pcb_port_id: "port_r5_1",
              shape: "rect",
              x: -9.75,
              y: 8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r5_2",
              pcb_component_id: "pcb_resistor_5",
              pcb_port_id: "port_r5_2",
              shape: "rect",
              x: -7.25,
              y: 8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_6",
              source_component_id: "resistor_6",
              center: { x: -5.5, y: 8 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r6_1",
              pcb_component_id: "pcb_resistor_6",
              pcb_port_id: "port_r6_1",
              shape: "rect",
              x: -6.75,
              y: 8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r6_2",
              pcb_component_id: "pcb_resistor_6",
              pcb_port_id: "port_r6_2",
              shape: "rect",
              x: -4.25,
              y: 8,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_3",
              name: "Group Relative to Board",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_3",
              source_group_id: "source_group_3",
              name: "Group Relative to Board",
              center: { x: -7, y: 8 },
              width: 7,
              height: 3,
              anchor_position: { x: -7, y: 8 },
              anchor_alignment: "center",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_board_id: "pcb_board_0",
              display_offset_x: "Board Δx: -7.00mm",
              display_offset_y: "Board Δy: 8.00mm",
              pcb_component_ids: ["pcb_resistor_5", "pcb_resistor_6"],
            },
          ] as AnyCircuitElement[]
        }
      />
    </div>
  )
}

export default GroupToGroupAndBoardAnchor
