import type React from "react"
import { PCBViewer } from "../PCBViewer"
import { AnyCircuitElement } from "circuit-json"

export const GroupAnchorHoverOffset: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        circuitJson={
          [
            {
              type: "source_component",
              source_component_id: "resistor_1",
              name: "R1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_2",
              name: "R2",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "capacitor_1",
              name: "C1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "led_1",
              name: "LED1",
              supplier_part_numbers: {},
            },
            // Group 1 - Center aligned with components at different offsets
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_1",
              source_component_id: "resistor_1",
              center: { x: -2, y: 1 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_1",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_1",
              shape: "rect",
              x: -3.25,
              y: 1,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_2",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_2",
              shape: "rect",
              x: -0.75,
              y: 1,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_2",
              source_component_id: "resistor_2",
              center: { x: 2, y: -1 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_1",
              pcb_component_id: "pcb_resistor_2",
              pcb_port_id: "port_r2_1",
              shape: "rect",
              x: 0.75,
              y: -1,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_2",
              pcb_component_id: "pcb_resistor_2",
              pcb_port_id: "port_r2_2",
              shape: "rect",
              x: 3.25,
              y: -1,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_1",
              name: "Center Group",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_1",
              source_group_id: "source_group_1",
              name: "Center Group",
              center: { x: 0, y: 0 },
              width: 8,
              height: 4,
              anchor_position: { x: 0, y: 0 },
              anchor_alignment: "center",
              pcb_component_ids: ["pcb_resistor_1", "pcb_resistor_2"],
            },
            // Group 2 - Top left anchor with offset components
            {
              type: "pcb_component",
              pcb_component_id: "pcb_capacitor_1",
              source_component_id: "capacitor_1",
              center: { x: -8, y: 7 },
              width: 2,
              height: 2.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c1_1",
              pcb_component_id: "pcb_capacitor_1",
              pcb_port_id: "port_c1_1",
              shape: "rect",
              x: -8,
              y: 7.8,
              width: 1.5,
              height: 0.7,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c1_2",
              pcb_component_id: "pcb_capacitor_1",
              pcb_port_id: "port_c1_2",
              shape: "rect",
              x: -8,
              y: 6.2,
              width: 1.5,
              height: 0.7,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_led_1",
              source_component_id: "led_1",
              center: { x: -5, y: 7 },
              width: 2,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_led_1",
              pcb_component_id: "pcb_led_1",
              pcb_port_id: "port_led_1",
              shape: "rect",
              x: -5.5,
              y: 7,
              width: 0.8,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_led_2",
              pcb_component_id: "pcb_led_1",
              pcb_port_id: "port_led_2",
              shape: "rect",
              x: -4.5,
              y: 7,
              width: 0.8,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_2",
              name: "Top Left Circuit",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_2",
              source_group_id: "source_group_2",
              name: "Top Left Circuit",
              center: { x: -6.5, y: 7 },
              width: 5,
              height: 4,
              anchor_position: { x: -9, y: 9 },
              anchor_alignment: "top_left",
              pcb_component_ids: ["pcb_capacitor_1", "pcb_led_1"],
            },
            // Group 3 - Bottom right anchor
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_3",
              source_component_id: "resistor_1",
              center: { x: 7, y: -6 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 90,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_1",
              pcb_component_id: "pcb_resistor_3",
              pcb_port_id: "port_r3_1",
              shape: "rect",
              x: 7,
              y: -7.25,
              width: 1,
              height: 0.5,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_2",
              pcb_component_id: "pcb_resistor_3",
              pcb_port_id: "port_r3_2",
              shape: "rect",
              x: 7,
              y: -4.75,
              width: 1,
              height: 0.5,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_capacitor_2",
              source_component_id: "capacitor_1",
              center: { x: 9, y: -6 },
              width: 2,
              height: 2.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c2_1",
              pcb_component_id: "pcb_capacitor_2",
              pcb_port_id: "port_c2_1",
              shape: "rect",
              x: 9,
              y: -5.2,
              width: 1.5,
              height: 0.7,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_c2_2",
              pcb_component_id: "pcb_capacitor_2",
              pcb_port_id: "port_c2_2",
              shape: "rect",
              x: 9,
              y: -6.8,
              width: 1.5,
              height: 0.7,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_3",
              name: "Bottom Right Module",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_3",
              source_group_id: "source_group_3",
              name: "Bottom Right Module",
              center: { x: 8, y: -6 },
              width: 5,
              height: 4,
              anchor_position: { x: 10.5, y: -8 },
              anchor_alignment: "bottom_right",
              pcb_component_ids: ["pcb_resistor_3", "pcb_capacitor_2"],
            },
          ] as AnyCircuitElement[]
        }
      />
    </div>
  )
}

export default GroupAnchorHoverOffset
