import type React from "react"
import { PCBViewer } from "../PCBViewer"
import { AnyCircuitElement } from "circuit-json"

/**
 * Fixture demonstrating nested group anchor offset detection.
 *
 * Structure:
 * - Group A (Base Group): Components R1, R2
 * - Group B: Positioned relative to Group A's anchor, contains R3, R4
 * - Group C: Positioned relative to Group B's anchor, contains R5, R6
 *
 * When hovering components in Group C, the hover detection should traverse
 * up the hierarchy and show offsets to both Group B and Group A anchors.
 */
export const NestedGroupAnchorOffset: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        initialState={{
          is_showing_pcb_groups: true,
          is_showing_group_anchor_offsets: true,
        }}
        circuitJson={
          [
            {
              type: "source_component",
              source_component_id: "resistor_1",
              name: "R1",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_2",
              name: "R2",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_3",
              name: "R3",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_4",
              name: "R4",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_5",
              name: "R5",
              supplier_part_numbers: {},
            },
            {
              type: "source_component",
              source_component_id: "resistor_6",
              name: "R6",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_board",
              pcb_board_id: "pcb_board_0",
              center: { x: 0, y: 0 },
              width: 50,
              height: 40,
              thickness: 1.6,
              num_layers: 4,
              material: "fr4",
            },
            // Group A - Base Group (left side)
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_1",
              source_component_id: "resistor_1",
              center: { x: -15, y: -10 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_a",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_1",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_1",
              shape: "rect",
              x: -16.25,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r1_2",
              pcb_component_id: "pcb_resistor_1",
              pcb_port_id: "port_r1_2",
              shape: "rect",
              x: -13.75,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_2",
              source_component_id: "resistor_2",
              center: { x: -12, y: -10 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_a",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_1",
              pcb_component_id: "pcb_resistor_2",
              pcb_port_id: "port_r2_1",
              shape: "rect",
              x: -13.25,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r2_2",
              pcb_component_id: "pcb_resistor_2",
              pcb_port_id: "port_r2_2",
              shape: "rect",
              x: -10.75,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_a",
              name: "Group A (Base)",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_a",
              source_group_id: "source_group_a",
              name: "Group A (Base)",
              center: { x: -13.5, y: -10 },
              width: 6,
              height: 3,
              anchor_position: { x: -13.5, y: -10 },
              anchor_alignment: "center",
              pcb_component_ids: ["pcb_resistor_1", "pcb_resistor_2"],
            },
            // Group B - Positioned relative to Group A's anchor (middle)
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_3",
              source_component_id: "resistor_3",
              center: { x: 0, y: -10 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_b",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_1",
              pcb_component_id: "pcb_resistor_3",
              pcb_port_id: "port_r3_1",
              shape: "rect",
              x: -1.25,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r3_2",
              pcb_component_id: "pcb_resistor_3",
              pcb_port_id: "port_r3_2",
              shape: "rect",
              x: 1.25,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_4",
              source_component_id: "resistor_4",
              center: { x: 3, y: -10 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_b",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r4_1",
              pcb_component_id: "pcb_resistor_4",
              pcb_port_id: "port_r4_1",
              shape: "rect",
              x: 1.75,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r4_2",
              pcb_component_id: "pcb_resistor_4",
              pcb_port_id: "port_r4_2",
              shape: "rect",
              x: 4.25,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_b",
              name: "Group B (Relative to A)",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_b",
              source_group_id: "source_group_b",
              name: "Group B (Relative to A)",
              center: { x: 1.5, y: -10 },
              width: 6,
              height: 3,
              anchor_position: { x: 1.5, y: -10 },
              anchor_alignment: "center",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_a",
              display_offset_x: "Group A 15.00",
              display_offset_y: "Group A 0.00",
              pcb_component_ids: ["pcb_resistor_3", "pcb_resistor_4"],
            },
            // Group C - Positioned relative to Group B's anchor (right side, 3 levels deep)
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_5",
              source_component_id: "resistor_5",
              center: { x: 15, y: -10 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_c",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r5_1",
              pcb_component_id: "pcb_resistor_5",
              pcb_port_id: "port_r5_1",
              shape: "rect",
              x: 13.75,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r5_2",
              pcb_component_id: "pcb_resistor_5",
              pcb_port_id: "port_r5_2",
              shape: "rect",
              x: 16.25,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_6",
              source_component_id: "resistor_6",
              center: { x: 18, y: -10 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_c",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r6_1",
              pcb_component_id: "pcb_resistor_6",
              pcb_port_id: "port_r6_1",
              shape: "rect",
              x: 16.75,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_r6_2",
              pcb_component_id: "pcb_resistor_6",
              pcb_port_id: "port_r6_2",
              shape: "rect",
              x: 19.25,
              y: -10,
              width: 0.5,
              height: 1,
              layer: "top",
            },
            {
              type: "source_group",
              source_group_id: "source_group_c",
              name: "Group C (Relative to B)",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_c",
              source_group_id: "source_group_c",
              name: "Group C (Relative to B)",
              center: { x: 16.5, y: -10 },
              width: 6,
              height: 3,
              anchor_position: { x: 16.5, y: -10 },
              anchor_alignment: "center",
              position_mode: "relative_to_group_anchor",
              positioned_relative_to_pcb_group_id: "group_b",
              display_offset_x: "Group B 15.00",
              display_offset_y: "Group B 0.00",
              pcb_component_ids: ["pcb_resistor_5", "pcb_resistor_6"],
            },
          ] as AnyCircuitElement[]
        }
      />
    </div>
  )
}

export default NestedGroupAnchorOffset
