import type React from "react"
import { PCBViewer } from "../PCBViewer"

export const PcbGroupWithAnchor: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        circuitJson={
          [
            // Group 1 - Center alignment
            {
              type: "source_component",
              source_component_id: "resistor_1",
              name: "R1",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_1",
              source_component_id: "resistor_1",
              center: { x: 0, y: 0 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_1_1",
              pcb_component_id: "pcb_resistor_1",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: -1.1,
              y: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_1_2",
              pcb_component_id: "pcb_resistor_1",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 1.1,
              y: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "source_component",
              source_component_id: "resistor_2",
              name: "R2",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_2",
              source_component_id: "resistor_2",
              center: { x: 5, y: 0 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_2_1",
              pcb_component_id: "pcb_resistor_2",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 3.9,
              y: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_2_2",
              pcb_component_id: "pcb_resistor_2",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 6.1,
              y: 0,
              pcb_group_id: "group_1",
            },
            {
              type: "source_group",
              source_group_id: "source_group_1",
              name: "Resistor Group",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_1",
              source_group_id: "source_group_1",
              name: "Resistor Group",
              center: { x: 2.5, y: 0 },
              width: 8,
              height: 2.5,
              anchor_position: { x: 2.5, y: 0 },
              anchor_alignment: "center",
              pcb_component_ids: ["pcb_resistor_1", "pcb_resistor_2"],
            },

            // Group 2 - Top left alignment
            {
              type: "source_component",
              source_component_id: "resistor_3",
              name: "R3",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_3",
              source_component_id: "resistor_3",
              center: { x: 0, y: 5 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_3_1",
              pcb_component_id: "pcb_resistor_3",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: -1.1,
              y: 5,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_3_2",
              pcb_component_id: "pcb_resistor_3",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 1.1,
              y: 5,
              pcb_group_id: "group_2",
            },
            {
              type: "source_component",
              source_component_id: "resistor_4",
              name: "R4",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_4",
              source_component_id: "resistor_4",
              center: { x: 5, y: 5 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_4_1",
              pcb_component_id: "pcb_resistor_4",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 3.9,
              y: 5,
              pcb_group_id: "group_2",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_4_2",
              pcb_component_id: "pcb_resistor_4",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 6.1,
              y: 5,
              pcb_group_id: "group_2",
            },
            {
              type: "source_group",
              source_group_id: "source_group_2",
              name: "Another Group",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_2",
              source_group_id: "source_group_2",
              name: "Another Group",
              center: { x: 2.5, y: 5 },
              width: 8,
              height: 2.5,
              anchor_position: { x: 0, y: 5 },
              anchor_alignment: "top_left",
              pcb_component_ids: ["pcb_resistor_3", "pcb_resistor_4"],
            },

            // Group 3 - Bottom right alignment
            {
              type: "source_component",
              source_component_id: "resistor_5",
              name: "R5",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_5",
              source_component_id: "resistor_5",
              center: { x: 0, y: -5 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_5_1",
              pcb_component_id: "pcb_resistor_5",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: -1.1,
              y: -5,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_5_2",
              pcb_component_id: "pcb_resistor_5",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 1.1,
              y: -5,
              pcb_group_id: "group_3",
            },
            {
              type: "source_component",
              source_component_id: "resistor_6",
              name: "R6",
              supplier_part_numbers: {},
            },
            {
              type: "pcb_component",
              pcb_component_id: "pcb_resistor_6",
              source_component_id: "resistor_6",
              center: { x: 5, y: -5 },
              width: 3,
              height: 1.5,
              layer: "top",
              rotation: 0,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_6_1",
              pcb_component_id: "pcb_resistor_6",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 3.9,
              y: -5,
              pcb_group_id: "group_3",
            },
            {
              type: "pcb_smtpad",
              pcb_smtpad_id: "pad_6_2",
              pcb_component_id: "pcb_resistor_6",
              layer: "top",
              shape: "rect",
              width: 0.8,
              height: 1.2,
              x: 6.1,
              y: -5,
              pcb_group_id: "group_3",
            },
            {
              type: "source_group",
              source_group_id: "source_group_3",
              name: "Bottom Right Group",
            },
            {
              type: "pcb_group",
              pcb_group_id: "group_3",
              source_group_id: "source_group_3",
              name: "Bottom Right Group",
              center: { x: 2.5, y: -5 },
              width: 8,
              height: 2.5,
              anchor_position: { x: 5, y: -5 },
              anchor_alignment: "bottom_right",
              pcb_component_ids: ["pcb_resistor_5", "pcb_resistor_6"],
            },
          ] as any
        }
      />
    </div>
  )
}

export default PcbGroupWithAnchor
