import { PCBViewer } from "../PCBViewer"

const circuitJson = [
  {
    type: "source_project_metadata",
    source_project_metadata_id: "source_project_metadata_0",
    software_used_string: "@tscircuit/core@0.0.616",
  },
  {
    type: "source_group",
    source_group_id: "source_group_0",
    name: "Alpha Node",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_1",
    name: "Blue Bridge",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_2",
    name: "Copper Point",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_3",
    name: "Echo Ridge",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_4",
    name: "Delta Gate",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_5",
    name: "Flux Node",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_6",
    name: "Silver Pad",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_7",
    name: "Gamma Port",
    parent_source_group_id: "source_group_8",
  },
  {
    type: "source_group",
    source_group_id: "source_group_8",
    is_subcircuit: true,
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_port",
    source_port_id: "source_port_0",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "anode", "pos", "left", "1"],
    source_component_id: "source_component_0",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net0",
  },
  {
    type: "source_port",
    source_port_id: "source_port_1",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "cathode", "neg", "right", "2"],
    source_component_id: "source_component_0",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_0",
    ftype: "simple_resistor",
    name: "R1",
    supplier_part_numbers: {
      jlcpcb: ["C25086", "C185446", "C2906901"],
    },
    resistance: 1000,
    display_resistance: "1kΩ",
    are_pins_interchangeable: true,
    source_group_id: "source_group_0",
  },
  {
    type: "source_port",
    source_port_id: "source_port_2",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "pos", "1"],
    source_component_id: "source_component_1",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net0",
  },
  {
    type: "source_port",
    source_port_id: "source_port_3",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "neg", "2"],
    source_component_id: "source_component_1",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_1",
    ftype: "simple_capacitor",
    name: "C1",
    supplier_part_numbers: {
      jlcpcb: ["C696907", "C1523", "C77018"],
    },
    capacitance: 1e-9,
    display_capacitance: "1nF",
    are_pins_interchangeable: true,
    source_group_id: "source_group_0",
  },
  {
    type: "source_port",
    source_port_id: "source_port_4",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "anode", "pos", "left", "1"],
    source_component_id: "source_component_2",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net1",
  },
  {
    type: "source_port",
    source_port_id: "source_port_5",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "cathode", "neg", "right", "2"],
    source_component_id: "source_component_2",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_2",
    ftype: "simple_resistor",
    name: "R2",
    resistance: 4700,
    display_resistance: "4.7kΩ",
    are_pins_interchangeable: true,
    source_group_id: "source_group_1",
  },
  {
    type: "source_port",
    source_port_id: "source_port_6",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "pos", "1"],
    source_component_id: "source_component_3",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net1",
  },
  {
    type: "source_port",
    source_port_id: "source_port_7",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "neg", "2"],
    source_component_id: "source_component_3",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_3",
    ftype: "simple_capacitor",
    name: "C2",
    capacitance: 2.2e-7,
    display_capacitance: "220nF",
    are_pins_interchangeable: true,
    source_group_id: "source_group_1",
  },
  {
    type: "source_port",
    source_port_id: "source_port_8",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "anode", "pos", "left", "1"],
    source_component_id: "source_component_4",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_port",
    source_port_id: "source_port_9",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "cathode", "neg", "right", "2"],
    source_component_id: "source_component_4",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_4",
    ftype: "simple_resistor",
    name: "R3",
    resistance: 10000,
    display_resistance: "10kΩ",
    are_pins_interchangeable: true,
    source_group_id: "source_group_2",
  },
  {
    type: "source_port",
    source_port_id: "source_port_10",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "pos", "1"],
    source_component_id: "source_component_5",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_port",
    source_port_id: "source_port_11",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "neg", "2"],
    source_component_id: "source_component_5",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_5",
    ftype: "simple_capacitor",
    name: "C4",
    capacitance: 0.00001,
    display_capacitance: "10µF",
    are_pins_interchangeable: true,
    source_group_id: "source_group_3",
  },
  {
    type: "source_port",
    source_port_id: "source_port_12",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "anode", "pos", "left", "1"],
    source_component_id: "source_component_6",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net2",
  },
  {
    type: "source_port",
    source_port_id: "source_port_13",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "cathode", "neg", "right", "2"],
    source_component_id: "source_component_6",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_6",
    ftype: "simple_resistor",
    name: "R5",
    resistance: 220,
    display_resistance: "220Ω",
    are_pins_interchangeable: true,
    source_group_id: "source_group_4",
  },
  {
    type: "source_port",
    source_port_id: "source_port_14",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "pos", "1"],
    source_component_id: "source_component_7",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net2",
  },
  {
    type: "source_port",
    source_port_id: "source_port_15",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "neg", "2"],
    source_component_id: "source_component_7",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_7",
    ftype: "simple_capacitor",
    name: "C5",
    capacitance: 4.7e-10,
    display_capacitance: "470pF",
    are_pins_interchangeable: true,
    source_group_id: "source_group_4",
  },
  {
    type: "source_port",
    source_port_id: "source_port_16",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "anode", "pos", "left", "1"],
    source_component_id: "source_component_8",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_port",
    source_port_id: "source_port_17",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "cathode", "neg", "right", "2"],
    source_component_id: "source_component_8",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_8",
    ftype: "simple_resistor",
    name: "R6",
    resistance: 330,
    display_resistance: "330Ω",
    are_pins_interchangeable: true,
    source_group_id: "source_group_5",
  },
  {
    type: "source_port",
    source_port_id: "source_port_18",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "pos", "1"],
    source_component_id: "source_component_9",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_port",
    source_port_id: "source_port_19",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "neg", "2"],
    source_component_id: "source_component_9",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_9",
    ftype: "simple_capacitor",
    name: "C7",
    capacitance: 0.000001,
    display_capacitance: "1µF",
    are_pins_interchangeable: true,
    source_group_id: "source_group_6",
  },
  {
    type: "source_port",
    source_port_id: "source_port_20",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "anode", "pos", "left", "1"],
    source_component_id: "source_component_10",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net3",
  },
  {
    type: "source_port",
    source_port_id: "source_port_21",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "cathode", "neg", "right", "2"],
    source_component_id: "source_component_10",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_10",
    ftype: "simple_resistor",
    name: "R8",
    resistance: 5600,
    display_resistance: "5.6kΩ",
    are_pins_interchangeable: true,
    source_group_id: "source_group_7",
  },
  {
    type: "source_port",
    source_port_id: "source_port_22",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "pos", "1"],
    source_component_id: "source_component_11",
    subcircuit_id: "subcircuit_source_group_8",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net3",
  },
  {
    type: "source_port",
    source_port_id: "source_port_23",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "neg", "2"],
    source_component_id: "source_component_11",
    subcircuit_id: "subcircuit_source_group_8",
  },
  {
    type: "source_component",
    source_component_id: "source_component_11",
    ftype: "simple_capacitor",
    name: "C8",
    capacitance: 3.3e-10,
    display_capacitance: "330pF",
    are_pins_interchangeable: true,
    source_group_id: "source_group_7",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_0",
    connected_source_port_ids: ["source_port_0", "source_port_2"],
    connected_source_net_ids: [],
    subcircuit_id: "subcircuit_source_group_8",
    max_length: null,
    display_name: ".R1 > .pin1 to .C1 > .pin1",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net0",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_1",
    connected_source_port_ids: ["source_port_4", "source_port_6"],
    connected_source_net_ids: [],
    subcircuit_id: "subcircuit_source_group_8",
    max_length: null,
    display_name: ".R2 > .pin1 to .C2 > .pin1",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net1",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_2",
    connected_source_port_ids: ["source_port_12", "source_port_14"],
    connected_source_net_ids: [],
    subcircuit_id: "subcircuit_source_group_8",
    max_length: null,
    display_name: ".R5 > .pin1 to .C5 > .pin1",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net2",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_3",
    connected_source_port_ids: ["source_port_20", "source_port_22"],
    connected_source_net_ids: [],
    subcircuit_id: "subcircuit_source_group_8",
    max_length: null,
    display_name: ".R8 > .pin1 to .C8 > .pin1",
    subcircuit_connectivity_map_key: "unnamedsubcircuit1036_connectivity_net3",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_0",
    center: {
      x: 3,
      y: 0,
    },
    size: {
      width: 1.0583332999999997,
      height: 0.388910699999999,
    },
    source_component_id: "source_component_0",
    symbol_name: "boxresistor_right",
    symbol_display_value: "1kΩ",
    schematic_group_id: "schematic_group_0",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_1",
    center: {
      x: -3,
      y: 0,
    },
    size: {
      width: 1.0583333000000001,
      height: 0.8400173000000031,
    },
    source_component_id: "source_component_1",
    symbol_name: "capacitor_right",
    symbol_display_value: "1nF",
    schematic_group_id: "schematic_group_0",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_0",
    subcircuit_id: null,
    name: "Alpha Node",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_0",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_2",
    center: {
      x: 2,
      y: 0,
    },
    size: {
      width: 1.0583332999999997,
      height: 0.388910699999999,
    },
    source_component_id: "source_component_2",
    symbol_name: "boxresistor_right",
    symbol_display_value: "4.7kΩ",
    schematic_group_id: "schematic_group_1",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_3",
    center: {
      x: -2,
      y: 0,
    },
    size: {
      width: 1.0583333000000001,
      height: 0.8400173000000031,
    },
    source_component_id: "source_component_3",
    symbol_name: "capacitor_right",
    symbol_display_value: "220nF",
    schematic_group_id: "schematic_group_1",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_1",
    subcircuit_id: null,
    name: "Blue Bridge",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_1",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_4",
    center: {
      x: 1,
      y: 0,
    },
    size: {
      width: 1.0583332999999997,
      height: 0.388910699999999,
    },
    source_component_id: "source_component_4",
    symbol_name: "boxresistor_right",
    symbol_display_value: "10kΩ",
    schematic_group_id: "schematic_group_2",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_2",
    subcircuit_id: null,
    name: "Copper Point",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_2",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_5",
    center: {
      x: -1,
      y: 0,
    },
    size: {
      width: 1.0583333000000001,
      height: 0.8400173000000031,
    },
    source_component_id: "source_component_5",
    symbol_name: "capacitor_right",
    symbol_display_value: "10µF",
    schematic_group_id: "schematic_group_3",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_3",
    subcircuit_id: null,
    name: "Echo Ridge",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_3",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_6",
    center: {
      x: 3,
      y: 0,
    },
    size: {
      width: 1.0583332999999997,
      height: 0.388910699999999,
    },
    source_component_id: "source_component_6",
    symbol_name: "boxresistor_right",
    symbol_display_value: "220Ω",
    schematic_group_id: "schematic_group_4",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_7",
    center: {
      x: -3,
      y: 0,
    },
    size: {
      width: 1.0583333000000001,
      height: 0.8400173000000031,
    },
    source_component_id: "source_component_7",
    symbol_name: "capacitor_right",
    symbol_display_value: "470pF",
    schematic_group_id: "schematic_group_4",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_4",
    subcircuit_id: null,
    name: "Delta Gate",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_4",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_8",
    center: {
      x: 2,
      y: 0,
    },
    size: {
      width: 1.0583332999999997,
      height: 0.388910699999999,
    },
    source_component_id: "source_component_8",
    symbol_name: "boxresistor_right",
    symbol_display_value: "330Ω",
    schematic_group_id: "schematic_group_5",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_5",
    subcircuit_id: null,
    name: "Flux Node",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_5",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_9",
    center: {
      x: -2,
      y: 0,
    },
    size: {
      width: 1.0583333000000001,
      height: 0.8400173000000031,
    },
    source_component_id: "source_component_9",
    symbol_name: "capacitor_right",
    symbol_display_value: "1µF",
    schematic_group_id: "schematic_group_6",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_6",
    subcircuit_id: null,
    name: "Silver Pad",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_6",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_10",
    center: {
      x: 2,
      y: 0,
    },
    size: {
      width: 1.0583332999999997,
      height: 0.388910699999999,
    },
    source_component_id: "source_component_10",
    symbol_name: "boxresistor_right",
    symbol_display_value: "5.6kΩ",
    schematic_group_id: "schematic_group_7",
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_component_11",
    center: {
      x: -2,
      y: 0,
    },
    size: {
      width: 1.0583333000000001,
      height: 0.8400173000000031,
    },
    source_component_id: "source_component_11",
    symbol_name: "capacitor_right",
    symbol_display_value: "330pF",
    schematic_group_id: "schematic_group_7",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_7",
    subcircuit_id: null,
    name: "Gamma Port",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_7",
  },
  {
    type: "schematic_group",
    schematic_group_id: "schematic_group_8",
    is_subcircuit: true,
    subcircuit_id: "subcircuit_source_group_8",
    name: "unnamed_board1",
    center: {
      x: 0,
      y: 0,
    },
    width: 0,
    height: 0,
    schematic_component_ids: [],
    source_group_id: "source_group_8",
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_0",
    schematic_component_id: "schematic_component_0",
    center: {
      x: 2.4487093,
      y: 0.0002732499999993365,
    },
    source_port_id: "source_port_0",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "anode",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_1",
    schematic_component_id: "schematic_component_0",
    center: {
      x: 3.5512907000000005,
      y: -0.0002732499999993365,
    },
    source_port_id: "source_port_1",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "cathode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_2",
    schematic_component_id: "schematic_component_1",
    center: {
      x: -3.5512093000000005,
      y: -0.00027334999999961695,
    },
    source_port_id: "source_port_2",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "pos",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_3",
    schematic_component_id: "schematic_component_1",
    center: {
      x: -2.4487907,
      y: 0.00027334999999961695,
    },
    source_port_id: "source_port_3",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "neg",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_4",
    schematic_component_id: "schematic_component_2",
    center: {
      x: 1.4487092999999998,
      y: 0.0002732499999993365,
    },
    source_port_id: "source_port_4",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "anode",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_5",
    schematic_component_id: "schematic_component_2",
    center: {
      x: 2.5512907000000005,
      y: -0.0002732499999993365,
    },
    source_port_id: "source_port_5",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "cathode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_6",
    schematic_component_id: "schematic_component_3",
    center: {
      x: -2.5512093,
      y: -0.00027334999999961695,
    },
    source_port_id: "source_port_6",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "pos",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_7",
    schematic_component_id: "schematic_component_3",
    center: {
      x: -1.4487906999999998,
      y: 0.00027334999999961695,
    },
    source_port_id: "source_port_7",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "neg",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_8",
    schematic_component_id: "schematic_component_4",
    center: {
      x: 0.44870929999999976,
      y: 0.0002732499999993365,
    },
    source_port_id: "source_port_8",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "anode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_9",
    schematic_component_id: "schematic_component_4",
    center: {
      x: 1.5512907000000005,
      y: -0.0002732499999993365,
    },
    source_port_id: "source_port_9",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "cathode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_10",
    schematic_component_id: "schematic_component_5",
    center: {
      x: -1.5512093000000002,
      y: -0.00027334999999961695,
    },
    source_port_id: "source_port_10",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "pos",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_11",
    schematic_component_id: "schematic_component_5",
    center: {
      x: -0.44879069999999976,
      y: 0.00027334999999961695,
    },
    source_port_id: "source_port_11",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "neg",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_12",
    schematic_component_id: "schematic_component_6",
    center: {
      x: 2.4487093,
      y: 0.0002732499999993365,
    },
    source_port_id: "source_port_12",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "anode",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_13",
    schematic_component_id: "schematic_component_6",
    center: {
      x: 3.5512907000000005,
      y: -0.0002732499999993365,
    },
    source_port_id: "source_port_13",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "cathode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_14",
    schematic_component_id: "schematic_component_7",
    center: {
      x: -3.5512093000000005,
      y: -0.00027334999999961695,
    },
    source_port_id: "source_port_14",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "pos",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_15",
    schematic_component_id: "schematic_component_7",
    center: {
      x: -2.4487907,
      y: 0.00027334999999961695,
    },
    source_port_id: "source_port_15",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "neg",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_16",
    schematic_component_id: "schematic_component_8",
    center: {
      x: 1.4487092999999998,
      y: 0.0002732499999993365,
    },
    source_port_id: "source_port_16",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "anode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_17",
    schematic_component_id: "schematic_component_8",
    center: {
      x: 2.5512907000000005,
      y: -0.0002732499999993365,
    },
    source_port_id: "source_port_17",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "cathode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_18",
    schematic_component_id: "schematic_component_9",
    center: {
      x: -2.5512093,
      y: -0.00027334999999961695,
    },
    source_port_id: "source_port_18",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "pos",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_19",
    schematic_component_id: "schematic_component_9",
    center: {
      x: -1.4487906999999998,
      y: 0.00027334999999961695,
    },
    source_port_id: "source_port_19",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "neg",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_20",
    schematic_component_id: "schematic_component_10",
    center: {
      x: 1.4487092999999998,
      y: 0.0002732499999993365,
    },
    source_port_id: "source_port_20",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "anode",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_21",
    schematic_component_id: "schematic_component_10",
    center: {
      x: 2.5512907000000005,
      y: -0.0002732499999993365,
    },
    source_port_id: "source_port_21",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "cathode",
    is_connected: false,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_22",
    schematic_component_id: "schematic_component_11",
    center: {
      x: -2.5512093,
      y: -0.00027334999999961695,
    },
    source_port_id: "source_port_22",
    facing_direction: "left",
    distance_from_component_edge: 0.4,
    pin_number: 1,
    display_pin_label: "pos",
    is_connected: true,
  },
  {
    type: "schematic_port",
    schematic_port_id: "schematic_port_23",
    schematic_component_id: "schematic_component_11",
    center: {
      x: -1.4487906999999998,
      y: 0.00027334999999961695,
    },
    source_port_id: "source_port_23",
    facing_direction: "right",
    distance_from_component_edge: 0.4,
    pin_number: 2,
    display_pin_label: "neg",
    is_connected: false,
  },
  {
    type: "schematic_trace",
    schematic_trace_id: "schematic_trace_0",
    source_trace_id: "source_trace_0",
    edges: [
      {
        from: {
          route_type: "wire",
          x: 2.4487093,
          y: 0.0002732499999993365,
          width: 0.1,
          layer: "top",
        },
        to: {
          route_type: "wire",
          x: 2.4487093,
          y: 0.7200086500000016,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: 2.4487093,
          y: 0.7200086500000016,
          width: 0.1,
          layer: "top",
        },
        to: {
          route_type: "wire",
          x: -3.5512093000000005,
          y: 0.7200086500000016,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -3.5512093000000005,
          y: 0.7200086500000016,
          width: 0.1,
          layer: "top",
        },
        to: {
          route_type: "wire",
          x: -3.5512093000000005,
          y: 0.1497266500000004,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -3.5512093000000005,
          y: 0.1497266500000004,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: -3.5512093000000005,
          y: -0.00027334999999961695,
        },
      },
    ],
    junctions: [],
  },
  {
    type: "schematic_trace",
    schematic_trace_id: "schematic_trace_1",
    source_trace_id: "source_trace_1",
    edges: [
      {
        from: {
          route_type: "wire",
          x: 1.4487092999999998,
          y: 0.0002732499999993365,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: 1.4487092999999998,
          y: 0.6825086500000016,
        },
      },
      {
        from: {
          x: 1.4487092999999998,
          y: 0.6825086500000016,
        },
        to: {
          x: 1.4487092999999998,
          y: 0.7575086500000016,
        },
        is_crossing: true,
      },
      {
        from: {
          x: 1.4487092999999998,
          y: 0.7575086500000016,
        },
        to: {
          route_type: "wire",
          x: 1.4487092999999998,
          y: 0.8200086500000016,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: 1.4487092999999998,
          y: 0.8200086500000016,
          width: 0.1,
          layer: "top",
        },
        to: {
          route_type: "wire",
          x: -2.5512093,
          y: 0.8200086500000016,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -2.5512093,
          y: 0.8200086500000016,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: -2.5512093,
          y: 0.7575086500000016,
        },
      },
      {
        from: {
          x: -2.5512093,
          y: 0.7575086500000016,
        },
        to: {
          x: -2.5512093,
          y: 0.6825086500000016,
        },
        is_crossing: true,
      },
      {
        from: {
          x: -2.5512093,
          y: 0.6825086500000016,
        },
        to: {
          route_type: "wire",
          x: -2.5512093,
          y: 0.15027334999999964,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -2.5512093,
          y: 0.15027334999999964,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: -2.5512093,
          y: -0.00027334999999961695,
        },
      },
    ],
    junctions: [],
  },
  {
    type: "schematic_trace",
    schematic_trace_id: "schematic_trace_2",
    source_trace_id: "source_trace_2",
    edges: [
      {
        from: {
          x: 2.4487093,
          y: 0.0002732499999993365,
        },
        to: {
          x: 2.5487093,
          y: 0.0002732499999993365,
        },
      },
      {
        from: {
          route_type: "wire",
          x: 2.5487093,
          y: 0.0002732499999993365,
          width: 0.1,
          layer: "top",
        },
        to: {
          route_type: "wire",
          x: 2.5487093,
          y: 0.9200086500000015,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: 2.5487093,
          y: 0.9200086500000015,
          width: 0.1,
          layer: "top",
        },
        to: {
          route_type: "wire",
          x: -3.4512093000000004,
          y: 0.9200086500000015,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -3.4512093000000004,
          y: 0.9200086500000015,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: -3.4512093000000004,
          y: 0.7575086500000016,
        },
      },
      {
        from: {
          x: -3.4512093000000004,
          y: 0.7575086500000016,
        },
        to: {
          x: -3.4512093000000004,
          y: 0.6825086500000016,
        },
        is_crossing: true,
      },
      {
        from: {
          x: -3.4512093000000004,
          y: 0.6825086500000016,
        },
        to: {
          route_type: "wire",
          x: -3.4512093000000004,
          y: 0.1497266500000004,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -3.4512093000000004,
          y: 0.1497266500000004,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: -3.4512093000000004,
          y: -0.00027334999999961695,
        },
      },
      {
        from: {
          x: -3.4512093000000004,
          y: -0.00027334999999961695,
        },
        to: {
          x: -3.5512093000000005,
          y: -0.00027334999999961695,
        },
      },
    ],
    junctions: [],
  },
  {
    type: "schematic_trace",
    schematic_trace_id: "schematic_trace_3",
    source_trace_id: "source_trace_3",
    edges: [
      {
        from: {
          x: 1.4487092999999998,
          y: 0.0002732499999993365,
        },
        to: {
          x: 1.5487092999999998,
          y: 0.0002732499999993365,
        },
      },
      {
        from: {
          route_type: "wire",
          x: 1.5487092999999998,
          y: 0.0002732499999993365,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: 1.5487092999999998,
          y: 0.6825086500000016,
        },
      },
      {
        from: {
          x: 1.5487092999999998,
          y: 0.6825086500000016,
        },
        to: {
          x: 1.5487092999999998,
          y: 0.7575086500000016,
        },
        is_crossing: true,
      },
      {
        from: {
          x: 1.5487092999999998,
          y: 0.7575086500000016,
        },
        to: {
          x: 1.5487092999999998,
          y: 0.8825086500000016,
        },
      },
      {
        from: {
          x: 1.5487092999999998,
          y: 0.8825086500000016,
        },
        to: {
          x: 1.5487092999999998,
          y: 0.9575086500000015,
        },
        is_crossing: true,
      },
      {
        from: {
          x: 1.5487092999999998,
          y: 0.9575086500000015,
        },
        to: {
          route_type: "wire",
          x: 1.5487092999999998,
          y: 1.0200086500000016,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: 1.5487092999999998,
          y: 1.0200086500000016,
          width: 0.1,
          layer: "top",
        },
        to: {
          route_type: "wire",
          x: -2.4512093,
          y: 1.0200086500000016,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -2.4512093,
          y: 1.0200086500000016,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: -2.4512093,
          y: 0.9575086500000015,
        },
      },
      {
        from: {
          x: -2.4512093,
          y: 0.9575086500000015,
        },
        to: {
          x: -2.4512093,
          y: 0.8825086500000016,
        },
        is_crossing: true,
      },
      {
        from: {
          x: -2.4512093,
          y: 0.8825086500000016,
        },
        to: {
          x: -2.4512093,
          y: 0.8575086500000015,
        },
      },
      {
        from: {
          x: -2.4512093,
          y: 0.8575086500000015,
        },
        to: {
          x: -2.4512093,
          y: 0.7825086500000016,
        },
        is_crossing: true,
      },
      {
        from: {
          x: -2.4512093,
          y: 0.7825086500000016,
        },
        to: {
          x: -2.4512093,
          y: 0.7575086500000016,
        },
      },
      {
        from: {
          x: -2.4512093,
          y: 0.7575086500000016,
        },
        to: {
          x: -2.4512093,
          y: 0.6825086500000016,
        },
        is_crossing: true,
      },
      {
        from: {
          x: -2.4512093,
          y: 0.6825086500000016,
        },
        to: {
          route_type: "wire",
          x: -2.4512093,
          y: 0.15027334999999964,
          width: 0.1,
          layer: "top",
        },
      },
      {
        from: {
          route_type: "wire",
          x: -2.4512093,
          y: 0.15027334999999964,
          width: 0.1,
          layer: "top",
        },
        to: {
          x: -2.4512093,
          y: -0.00027334999999961695,
        },
      },
      {
        from: {
          x: -2.4512093,
          y: -0.00027334999999961695,
        },
        to: {
          x: -2.5512093,
          y: -0.00027334999999961695,
        },
      },
    ],
    junctions: [],
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_0",
    center: {
      x: -7,
      y: 10,
    },
    width: 1.5999999999999996,
    height: 0.6000000000000014,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_0",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_1",
    center: {
      x: -13,
      y: 10,
    },
    width: 1.6000000000000014,
    height: 0.6000000000000014,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_1",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_0",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Alpha Node",
    center: {
      x: -10,
      y: 10,
    },
    width: 7.6000000000000005,
    height: 0.6000000000000014,
    pcb_component_ids: [],
    source_group_id: "source_group_0",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_2",
    center: {
      x: 17,
      y: -5,
    },
    width: 2.8000000000000043,
    height: 1,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_2",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_3",
    center: {
      x: 13,
      y: -5,
    },
    width: 2.8000000000000007,
    height: 1,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_3",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_1",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Blue Bridge",
    center: {
      x: 15,
      y: -5,
    },
    width: 6.8000000000000025,
    height: 1,
    pcb_component_ids: [],
    source_group_id: "source_group_1",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_4",
    center: {
      x: -19,
      y: -15,
    },
    width: 3,
    height: 1.1999999999999993,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_4",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_2",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Copper Point",
    center: {
      x: -19,
      y: -15,
    },
    width: 3,
    height: 1.1999999999999993,
    pcb_component_ids: [],
    source_group_id: "source_group_2",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_5",
    center: {
      x: 4,
      y: 20,
    },
    width: 3,
    height: 1.2000000000000028,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_5",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_3",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Echo Ridge",
    center: {
      x: 4,
      y: 20,
    },
    width: 3,
    height: 1.2000000000000028,
    pcb_component_ids: [],
    source_group_id: "source_group_3",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_6",
    center: {
      x: 15,
      y: 12,
    },
    width: 1.6000000000000014,
    height: 0.6000000000000014,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_6",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_7",
    center: {
      x: 9,
      y: 12,
    },
    width: 1.6000000000000014,
    height: 0.6000000000000014,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_7",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_4",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Delta Gate",
    center: {
      x: 12,
      y: 12,
    },
    width: 7.600000000000001,
    height: 0.6000000000000014,
    pcb_component_ids: [],
    source_group_id: "source_group_4",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_8",
    center: {
      x: -6,
      y: -8,
    },
    width: 2.799999999999999,
    height: 1,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_8",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_5",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Flux Node",
    center: {
      x: -6,
      y: -8,
    },
    width: 2.799999999999999,
    height: 1,
    pcb_component_ids: [],
    source_group_id: "source_group_5",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_9",
    center: {
      x: 16,
      y: -12,
    },
    width: 2.8000000000000025,
    height: 1,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_9",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_6",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Silver Pad",
    center: {
      x: 16,
      y: -12,
    },
    width: 2.8000000000000025,
    height: 1,
    pcb_component_ids: [],
    source_group_id: "source_group_6",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_10",
    center: {
      x: -12,
      y: 6,
    },
    width: 1.6000000000000014,
    height: 0.5999999999999996,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_10",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_11",
    center: {
      x: -16,
      y: 6,
    },
    width: 1.6000000000000014,
    height: 0.5999999999999996,
    layer: "top",
    rotation: 0,
    source_component_id: "source_component_11",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_group",
    pcb_group_id: "pcb_group_7",
    subcircuit_id: "subcircuit_source_group_8",
    name: "Gamma Port",
    center: {
      x: -14,
      y: 6,
    },
    width: 5.600000000000001,
    height: 0.5999999999999996,
    pcb_component_ids: [],
    source_group_id: "source_group_7",
  },
  {
    type: "pcb_board",
    pcb_board_id: "pcb_board_0",
    center: {
      x: -1.049999999999999,
      y: 2.500000000000001,
    },
    thickness: 1.4,
    num_layers: 2,
    width: 42.900000000000006,
    height: 40.2,
    material: "fr4",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_0",
    pcb_component_id: "pcb_component_0",
    pcb_port_id: "pcb_port_0",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["1", "left"],
    x: -7.5,
    y: 10,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_0",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -7.5,
    y: 10,
    pcb_component_id: "pcb_component_0",
    pcb_smtpad_id: "pcb_smtpad_0",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_1",
    pcb_component_id: "pcb_component_0",
    pcb_port_id: "pcb_port_1",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["2", "right"],
    x: -6.5,
    y: 10,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_1",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -6.5,
    y: 10,
    pcb_component_id: "pcb_component_0",
    pcb_smtpad_id: "pcb_smtpad_1",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_0",
    pcb_component_id: "pcb_component_0",
    layer: "top",
    route: [
      {
        x: -6.5,
        y: 10.7,
      },
      {
        x: -8,
        y: 10.7,
      },
      {
        x: -8,
        y: 9.3,
      },
      {
        x: -6.5,
        y: 9.3,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_0",
    anchor_alignment: "center",
    anchor_position: {
      x: -7,
      y: 11.2,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "R1",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_0",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_2",
    pcb_component_id: "pcb_component_1",
    pcb_port_id: "pcb_port_2",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["1", "left"],
    x: -13.5,
    y: 10,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_2",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -13.5,
    y: 10,
    pcb_component_id: "pcb_component_1",
    pcb_smtpad_id: "pcb_smtpad_2",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_3",
    pcb_component_id: "pcb_component_1",
    pcb_port_id: "pcb_port_3",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["2", "right"],
    x: -12.5,
    y: 10,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_3",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -12.5,
    y: 10,
    pcb_component_id: "pcb_component_1",
    pcb_smtpad_id: "pcb_smtpad_3",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_1",
    pcb_component_id: "pcb_component_1",
    layer: "top",
    route: [
      {
        x: -12.5,
        y: 10.7,
      },
      {
        x: -14,
        y: 10.7,
      },
      {
        x: -14,
        y: 9.3,
      },
      {
        x: -12.5,
        y: 9.3,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_1",
    anchor_alignment: "center",
    anchor_position: {
      x: -13,
      y: 11.2,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "C1",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_1",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_4",
    pcb_component_id: "pcb_component_2",
    pcb_port_id: "pcb_port_4",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["1", "left"],
    x: 16.15,
    y: -5,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_4",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: 16.15,
    y: -5,
    pcb_component_id: "pcb_component_2",
    pcb_smtpad_id: "pcb_smtpad_4",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_5",
    pcb_component_id: "pcb_component_2",
    pcb_port_id: "pcb_port_5",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["2", "right"],
    x: 17.85,
    y: -5,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_5",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: 17.85,
    y: -5,
    pcb_component_id: "pcb_component_2",
    pcb_smtpad_id: "pcb_smtpad_5",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_2",
    pcb_component_id: "pcb_component_2",
    layer: "top",
    route: [
      {
        x: 17.85,
        y: -4.1,
      },
      {
        x: 15.4,
        y: -4.1,
      },
      {
        x: 15.4,
        y: -5.9,
      },
      {
        x: 17.85,
        y: -5.9,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_2",
    anchor_alignment: "center",
    anchor_position: {
      x: 17,
      y: -3.6,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "R2",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_2",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_6",
    pcb_component_id: "pcb_component_3",
    pcb_port_id: "pcb_port_6",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["1", "left"],
    x: 12.15,
    y: -5,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_6",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: 12.15,
    y: -5,
    pcb_component_id: "pcb_component_3",
    pcb_smtpad_id: "pcb_smtpad_6",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_7",
    pcb_component_id: "pcb_component_3",
    pcb_port_id: "pcb_port_7",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["2", "right"],
    x: 13.85,
    y: -5,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_7",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: 13.85,
    y: -5,
    pcb_component_id: "pcb_component_3",
    pcb_smtpad_id: "pcb_smtpad_7",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_3",
    pcb_component_id: "pcb_component_3",
    layer: "top",
    route: [
      {
        x: 13.85,
        y: -4.1,
      },
      {
        x: 11.4,
        y: -4.1,
      },
      {
        x: 11.4,
        y: -5.9,
      },
      {
        x: 13.85,
        y: -5.9,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_3",
    anchor_alignment: "center",
    anchor_position: {
      x: 13,
      y: -3.6,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "C2",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_3",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_8",
    pcb_component_id: "pcb_component_4",
    pcb_port_id: "pcb_port_8",
    layer: "top",
    shape: "rect",
    width: 0.85,
    height: 1.2,
    port_hints: ["1", "left"],
    x: -20.075,
    y: -15,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_8",
    layer: "top",
    shape: "rect",
    width: 0.595,
    height: 0.84,
    x: -20.075,
    y: -15,
    pcb_component_id: "pcb_component_4",
    pcb_smtpad_id: "pcb_smtpad_8",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_9",
    pcb_component_id: "pcb_component_4",
    pcb_port_id: "pcb_port_9",
    layer: "top",
    shape: "rect",
    width: 0.85,
    height: 1.2,
    port_hints: ["2", "right"],
    x: -17.925,
    y: -15,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_9",
    layer: "top",
    shape: "rect",
    width: 0.595,
    height: 0.84,
    x: -17.925,
    y: -15,
    pcb_component_id: "pcb_component_4",
    pcb_smtpad_id: "pcb_smtpad_9",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_4",
    pcb_component_id: "pcb_component_4",
    layer: "top",
    route: [
      {
        x: -17.925,
        y: -14,
      },
      {
        x: -20.7,
        y: -14,
      },
      {
        x: -20.7,
        y: -16,
      },
      {
        x: -17.925,
        y: -16,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_4",
    anchor_alignment: "center",
    anchor_position: {
      x: -19,
      y: -13.5,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "R3",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_4",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_10",
    pcb_component_id: "pcb_component_5",
    pcb_port_id: "pcb_port_10",
    layer: "top",
    shape: "rect",
    width: 0.85,
    height: 1.2,
    port_hints: ["1", "left"],
    x: 2.925,
    y: 20,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_10",
    layer: "top",
    shape: "rect",
    width: 0.595,
    height: 0.84,
    x: 2.925,
    y: 20,
    pcb_component_id: "pcb_component_5",
    pcb_smtpad_id: "pcb_smtpad_10",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_11",
    pcb_component_id: "pcb_component_5",
    pcb_port_id: "pcb_port_11",
    layer: "top",
    shape: "rect",
    width: 0.85,
    height: 1.2,
    port_hints: ["2", "right"],
    x: 5.075,
    y: 20,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_11",
    layer: "top",
    shape: "rect",
    width: 0.595,
    height: 0.84,
    x: 5.075,
    y: 20,
    pcb_component_id: "pcb_component_5",
    pcb_smtpad_id: "pcb_smtpad_11",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_5",
    pcb_component_id: "pcb_component_5",
    layer: "top",
    route: [
      {
        x: 5.075,
        y: 21,
      },
      {
        x: 2.3,
        y: 21,
      },
      {
        x: 2.3,
        y: 19,
      },
      {
        x: 5.075,
        y: 19,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_5",
    anchor_alignment: "center",
    anchor_position: {
      x: 4,
      y: 21.5,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "C4",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_5",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_12",
    pcb_component_id: "pcb_component_6",
    pcb_port_id: "pcb_port_12",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["1", "left"],
    x: 14.5,
    y: 12,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_12",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: 14.5,
    y: 12,
    pcb_component_id: "pcb_component_6",
    pcb_smtpad_id: "pcb_smtpad_12",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_13",
    pcb_component_id: "pcb_component_6",
    pcb_port_id: "pcb_port_13",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["2", "right"],
    x: 15.5,
    y: 12,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_13",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: 15.5,
    y: 12,
    pcb_component_id: "pcb_component_6",
    pcb_smtpad_id: "pcb_smtpad_13",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_6",
    pcb_component_id: "pcb_component_6",
    layer: "top",
    route: [
      {
        x: 15.5,
        y: 12.7,
      },
      {
        x: 14,
        y: 12.7,
      },
      {
        x: 14,
        y: 11.3,
      },
      {
        x: 15.5,
        y: 11.3,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_6",
    anchor_alignment: "center",
    anchor_position: {
      x: 15,
      y: 13.2,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "R5",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_6",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_14",
    pcb_component_id: "pcb_component_7",
    pcb_port_id: "pcb_port_14",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["1", "left"],
    x: 8.5,
    y: 12,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_14",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: 8.5,
    y: 12,
    pcb_component_id: "pcb_component_7",
    pcb_smtpad_id: "pcb_smtpad_14",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_15",
    pcb_component_id: "pcb_component_7",
    pcb_port_id: "pcb_port_15",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["2", "right"],
    x: 9.5,
    y: 12,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_15",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: 9.5,
    y: 12,
    pcb_component_id: "pcb_component_7",
    pcb_smtpad_id: "pcb_smtpad_15",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_7",
    pcb_component_id: "pcb_component_7",
    layer: "top",
    route: [
      {
        x: 9.5,
        y: 12.7,
      },
      {
        x: 8,
        y: 12.7,
      },
      {
        x: 8,
        y: 11.3,
      },
      {
        x: 9.5,
        y: 11.3,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_7",
    anchor_alignment: "center",
    anchor_position: {
      x: 9,
      y: 13.2,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "C5",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_7",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_16",
    pcb_component_id: "pcb_component_8",
    pcb_port_id: "pcb_port_16",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["1", "left"],
    x: -6.85,
    y: -8,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_16",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: -6.85,
    y: -8,
    pcb_component_id: "pcb_component_8",
    pcb_smtpad_id: "pcb_smtpad_16",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_17",
    pcb_component_id: "pcb_component_8",
    pcb_port_id: "pcb_port_17",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["2", "right"],
    x: -5.15,
    y: -8,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_17",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: -5.15,
    y: -8,
    pcb_component_id: "pcb_component_8",
    pcb_smtpad_id: "pcb_smtpad_17",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_8",
    pcb_component_id: "pcb_component_8",
    layer: "top",
    route: [
      {
        x: -5.15,
        y: -7.1,
      },
      {
        x: -7.6,
        y: -7.1,
      },
      {
        x: -7.6,
        y: -8.9,
      },
      {
        x: -5.15,
        y: -8.9,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_8",
    anchor_alignment: "center",
    anchor_position: {
      x: -6,
      y: -6.6,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "R6",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_8",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_18",
    pcb_component_id: "pcb_component_9",
    pcb_port_id: "pcb_port_18",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["1", "left"],
    x: 15.15,
    y: -12,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_18",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: 15.15,
    y: -12,
    pcb_component_id: "pcb_component_9",
    pcb_smtpad_id: "pcb_smtpad_18",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_19",
    pcb_component_id: "pcb_component_9",
    pcb_port_id: "pcb_port_19",
    layer: "top",
    shape: "rect",
    width: 1.1,
    height: 1,
    port_hints: ["2", "right"],
    x: 16.85,
    y: -12,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_19",
    layer: "top",
    shape: "rect",
    width: 0.77,
    height: 0.7,
    x: 16.85,
    y: -12,
    pcb_component_id: "pcb_component_9",
    pcb_smtpad_id: "pcb_smtpad_19",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_9",
    pcb_component_id: "pcb_component_9",
    layer: "top",
    route: [
      {
        x: 16.85,
        y: -11.1,
      },
      {
        x: 14.4,
        y: -11.1,
      },
      {
        x: 14.4,
        y: -12.9,
      },
      {
        x: 16.85,
        y: -12.9,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_9",
    anchor_alignment: "center",
    anchor_position: {
      x: 16,
      y: -10.6,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "C7",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_9",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_20",
    pcb_component_id: "pcb_component_10",
    pcb_port_id: "pcb_port_20",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["1", "left"],
    x: -12.5,
    y: 6,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_20",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -12.5,
    y: 6,
    pcb_component_id: "pcb_component_10",
    pcb_smtpad_id: "pcb_smtpad_20",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_21",
    pcb_component_id: "pcb_component_10",
    pcb_port_id: "pcb_port_21",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["2", "right"],
    x: -11.5,
    y: 6,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_21",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -11.5,
    y: 6,
    pcb_component_id: "pcb_component_10",
    pcb_smtpad_id: "pcb_smtpad_21",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_10",
    pcb_component_id: "pcb_component_10",
    layer: "top",
    route: [
      {
        x: -11.5,
        y: 6.7,
      },
      {
        x: -13,
        y: 6.7,
      },
      {
        x: -13,
        y: 5.3,
      },
      {
        x: -11.5,
        y: 5.3,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_10",
    anchor_alignment: "center",
    anchor_position: {
      x: -12,
      y: 7.2,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "R8",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_10",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_22",
    pcb_component_id: "pcb_component_11",
    pcb_port_id: "pcb_port_22",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["1", "left"],
    x: -16.5,
    y: 6,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_22",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -16.5,
    y: 6,
    pcb_component_id: "pcb_component_11",
    pcb_smtpad_id: "pcb_smtpad_22",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_23",
    pcb_component_id: "pcb_component_11",
    pcb_port_id: "pcb_port_23",
    layer: "top",
    shape: "rect",
    width: 0.6,
    height: 0.6,
    port_hints: ["2", "right"],
    x: -15.5,
    y: 6,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_solder_paste",
    pcb_solder_paste_id: "pcb_solder_paste_23",
    layer: "top",
    shape: "rect",
    width: 0.42,
    height: 0.42,
    x: -15.5,
    y: 6,
    pcb_component_id: "pcb_component_11",
    pcb_smtpad_id: "pcb_smtpad_23",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_silkscreen_path",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_11",
    pcb_component_id: "pcb_component_11",
    layer: "top",
    route: [
      {
        x: -15.5,
        y: 6.7,
      },
      {
        x: -17,
        y: 6.7,
      },
      {
        x: -17,
        y: 5.3,
      },
      {
        x: -15.5,
        y: 5.3,
      },
    ],
    stroke_width: 0.1,
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_silkscreen_text",
    pcb_silkscreen_text_id: "pcb_silkscreen_text_11",
    anchor_alignment: "center",
    anchor_position: {
      x: -16,
      y: 7.2,
    },
    font: "tscircuit2024",
    font_size: 0.4,
    layer: "top",
    text: "C8",
    ccw_rotation: 0,
    pcb_component_id: "pcb_component_11",
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_0",
    pcb_component_id: "pcb_component_0",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
    x: -7.5,
    y: 10,
    source_port_id: "source_port_0",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_1",
    pcb_component_id: "pcb_component_0",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
    x: -6.5,
    y: 10,
    source_port_id: "source_port_1",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_2",
    pcb_component_id: "pcb_component_1",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
    x: -13.5,
    y: 10,
    source_port_id: "source_port_2",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_3",
    pcb_component_id: "pcb_component_1",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_0",
    x: -12.5,
    y: 10,
    source_port_id: "source_port_3",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_4",
    pcb_component_id: "pcb_component_2",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
    x: 16.15,
    y: -5,
    source_port_id: "source_port_4",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_5",
    pcb_component_id: "pcb_component_2",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
    x: 17.85,
    y: -5,
    source_port_id: "source_port_5",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_6",
    pcb_component_id: "pcb_component_3",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
    x: 12.15,
    y: -5,
    source_port_id: "source_port_6",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_7",
    pcb_component_id: "pcb_component_3",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_1",
    x: 13.85,
    y: -5,
    source_port_id: "source_port_7",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_8",
    pcb_component_id: "pcb_component_4",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
    x: -20.075,
    y: -15,
    source_port_id: "source_port_8",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_9",
    pcb_component_id: "pcb_component_4",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_2",
    x: -17.925,
    y: -15,
    source_port_id: "source_port_9",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_10",
    pcb_component_id: "pcb_component_5",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
    x: 2.925,
    y: 20,
    source_port_id: "source_port_10",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_11",
    pcb_component_id: "pcb_component_5",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_3",
    x: 5.075,
    y: 20,
    source_port_id: "source_port_11",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_12",
    pcb_component_id: "pcb_component_6",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
    x: 14.5,
    y: 12,
    source_port_id: "source_port_12",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_13",
    pcb_component_id: "pcb_component_6",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
    x: 15.5,
    y: 12,
    source_port_id: "source_port_13",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_14",
    pcb_component_id: "pcb_component_7",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
    x: 8.5,
    y: 12,
    source_port_id: "source_port_14",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_15",
    pcb_component_id: "pcb_component_7",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_4",
    x: 9.5,
    y: 12,
    source_port_id: "source_port_15",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_16",
    pcb_component_id: "pcb_component_8",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
    x: -6.85,
    y: -8,
    source_port_id: "source_port_16",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_17",
    pcb_component_id: "pcb_component_8",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_5",
    x: -5.15,
    y: -8,
    source_port_id: "source_port_17",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_18",
    pcb_component_id: "pcb_component_9",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
    x: 15.15,
    y: -12,
    source_port_id: "source_port_18",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_19",
    pcb_component_id: "pcb_component_9",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_6",
    x: 16.85,
    y: -12,
    source_port_id: "source_port_19",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_20",
    pcb_component_id: "pcb_component_10",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
    x: -12.5,
    y: 6,
    source_port_id: "source_port_20",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_21",
    pcb_component_id: "pcb_component_10",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
    x: -11.5,
    y: 6,
    source_port_id: "source_port_21",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_22",
    pcb_component_id: "pcb_component_11",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
    x: -16.5,
    y: 6,
    source_port_id: "source_port_22",
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_23",
    pcb_component_id: "pcb_component_11",
    layers: ["top"],
    subcircuit_id: "subcircuit_source_group_8",
    pcb_group_id: "pcb_group_7",
    x: -15.5,
    y: 6,
    source_port_id: "source_port_23",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_0",
    position: {
      x: -7,
      y: 10,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_0",
    source_component_id: "source_component_0",
    footprinter_string: "0402",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_1",
    position: {
      x: -13,
      y: 10,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_1",
    source_component_id: "source_component_1",
    footprinter_string: "0402",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_2",
    position: {
      x: 17,
      y: -5,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_2",
    source_component_id: "source_component_2",
    footprinter_string: "0603",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_3",
    position: {
      x: 13,
      y: -5,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_3",
    source_component_id: "source_component_3",
    footprinter_string: "0603",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_4",
    position: {
      x: -19,
      y: -15,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_4",
    source_component_id: "source_component_4",
    footprinter_string: "0805",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_5",
    position: {
      x: 4,
      y: 20,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_5",
    source_component_id: "source_component_5",
    footprinter_string: "0805",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_6",
    position: {
      x: 15,
      y: 12,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_6",
    source_component_id: "source_component_6",
    footprinter_string: "0402",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_7",
    position: {
      x: 9,
      y: 12,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_7",
    source_component_id: "source_component_7",
    footprinter_string: "0402",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_8",
    position: {
      x: -6,
      y: -8,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_8",
    source_component_id: "source_component_8",
    footprinter_string: "0603",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_9",
    position: {
      x: 16,
      y: -12,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_9",
    source_component_id: "source_component_9",
    footprinter_string: "0603",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_10",
    position: {
      x: -12,
      y: 6,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_10",
    source_component_id: "source_component_10",
    footprinter_string: "0402",
  },
  {
    type: "cad_component",
    cad_component_id: "cad_component_11",
    position: {
      x: -16,
      y: 6,
      z: 0.7,
    },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    pcb_component_id: "pcb_component_11",
    source_component_id: "source_component_11",
    footprinter_string: "0402",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "source_trace_3_0",
    connection_name: "source_trace_3",
    route: [
      {
        route_type: "wire",
        x: -16.5,
        y: 6,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -15.95430357130099,
        y: 6.545696428699011,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -13.04569642869901,
        y: 6.545696428699011,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -13.04569642869901,
        y: 6.545696428699011,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -12.5,
        y: 6,
        width: 0.15,
        layer: "top",
      },
    ],
    subcircuit_id: "subcircuit_source_group_8",
    source_trace_id: "source_trace_3",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "source_trace_2_0",
    connection_name: "source_trace_2",
    route: [
      {
        route_type: "wire",
        x: 8.5,
        y: 12,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 5.864710475841418,
        y: 12,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 5.781072301121892,
        y: 11.916361825280473,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 5.653125000000005,
        y: 11.884375000000002,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "via",
        x: 5.653125000000005,
        y: 11.884375000000002,
        from_layer: "top",
        to_layer: "bottom",
      },
      {
        route_type: "wire",
        x: 5.653125000000005,
        y: 11.884375000000002,
        width: 0.15,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: 10.974579584186252,
        y: 11.884375000000002,
        width: 0.15,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: 11.634630730232812,
        y: 12.544426146046563,
        width: 0.15,
        layer: "bottom",
      },
      {
        route_type: "wire",
        x: 11.685937500000005,
        y: 12.554687500000002,
        width: 0.15,
        layer: "bottom",
      },
      {
        route_type: "via",
        x: 11.685937500000005,
        y: 12.554687500000002,
        from_layer: "bottom",
        to_layer: "top",
      },
      {
        route_type: "wire",
        x: 11.685937500000005,
        y: 12.554687500000002,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 13.945312499999998,
        y: 12.554687500000002,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 14.5,
        y: 12,
        width: 0.15,
        layer: "top",
      },
    ],
    subcircuit_id: "subcircuit_source_group_8",
    source_trace_id: "source_trace_2",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "source_trace_1_0",
    connection_name: "source_trace_1",
    route: [
      {
        route_type: "wire",
        x: 12.15,
        y: -5,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 12.858573338109771,
        y: -4.291426661890229,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 15.716042274765943,
        y: -4.291426661890229,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 15.716042274765943,
        y: -4.566042274765945,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 16.15,
        y: -5,
        width: 0.15,
        layer: "top",
      },
    ],
    subcircuit_id: "subcircuit_source_group_8",
    source_trace_id: "source_trace_1",
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "source_trace_0_0",
    connection_name: "source_trace_0",
    route: [
      {
        route_type: "wire",
        x: -13.5,
        y: 10,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -12.99441000851956,
        y: 9.49441000851956,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -7.900266613331874,
        y: 9.49441000851956,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -7.900266613331874,
        y: 9.599733386668126,
        width: 0.15,
        layer: "top",
      },
      {
        route_type: "wire",
        x: -7.5,
        y: 10,
        width: 0.15,
        layer: "top",
      },
    ],
    subcircuit_id: "subcircuit_source_group_8",
    source_trace_id: "source_trace_0",
  },
  {
    type: "pcb_via",
    pcb_via_id: "pcb_via_0",
    pcb_trace_id: "source_trace_2_0",
    x: 5.653125000000005,
    y: 11.884375000000002,
    hole_diameter: 0.3,
    outer_diameter: 0.6,
    layers: ["top", "bottom"],
    from_layer: "top",
    to_layer: "bottom",
  },
  {
    type: "pcb_via",
    pcb_via_id: "pcb_via_1",
    pcb_trace_id: "source_trace_2_0",
    x: 11.685937500000005,
    y: 12.554687500000002,
    hole_diameter: 0.3,
    outer_diameter: 0.6,
    layers: ["bottom", "top"],
    from_layer: "bottom",
    to_layer: "top",
  },
]
export const PcbGroups = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer circuitJson={circuitJson as any} />
    </div>
  )
}

export default {
  PcbGroups,
}
