import { Circuit } from "@tscircuit/core"
import { PCBViewer } from "../PCBViewer"

export const PlatedHolePillShape: React.FC = () => {
  return (
    <div style={{ backgroundColor: "black" }}>
      <PCBViewer
        circuitJson={
          [
            {
              type: "source_component",
              source_component_id: "generic_0",
              supplier_part_numbers: {},
            },
            {
              type: "schematic_component",
              schematic_component_id: "schematic_generic_component_0",
              source_component_id: "generic_0",
              center: { x: 0, y: 0 },
              rotation: 0,
              size: { width: 0, height: 0 },
            },
            {
              type: "pcb_component",
              source_component_id: "generic_0",
              pcb_component_id: "pcb_generic_component_0",
              layer: "top",
              center: { x: 0, y: 0 },
              rotation: 0,
              width: 0,
              height: 0,
            },
            {
              type: "pcb_plated_hole",
              x: 0,
              y: 0,
              layers: ["top", "bottom"],
              outer_width: 2.6,
              outer_height: 3.78,
              hole_width: 1.1,
              hole_height: 2.28,
              shape: "pill",
              port_hints: [],
              pcb_component_id: "pcb_generic_component_0",
            },
            {
              type: "pcb_silkscreen_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              pcb_silkscreen_path_id: "pcb_silkscreen_path_0",
              route: [
                { x: -0.515, y: 6.46 },
                { x: -0.515, y: 2.125 },
              ],
              stroke_width: 0.1,
            },
            {
              type: "pcb_silkscreen_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              pcb_silkscreen_path_id: "pcb_silkscreen_path_1",
              route: [
                { x: -0.515, y: 6.46 },
                { x: 12.405, y: 7.35 },
              ],
              stroke_width: 0.1,
            },
            {
              type: "pcb_silkscreen_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              pcb_silkscreen_path_id: "pcb_silkscreen_path_2",
              route: [
                { x: -0.515, y: -2.1 },
                { x: -0.515, y: -6.46 },
              ],
              stroke_width: 0.1,
            },
            {
              type: "pcb_silkscreen_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              pcb_silkscreen_path_id: "pcb_silkscreen_path_3",
              route: [
                { x: -0.515, y: -6.46 },
                { x: 12.405, y: -7.35 },
              ],
              stroke_width: 0.1,
            },
            {
              type: "pcb_silkscreen_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              pcb_silkscreen_path_id: "pcb_silkscreen_path_4",
              route: [
                { x: 12.405, y: 7.35 },
                { x: 12.405, y: -7.35 },
              ],
              stroke_width: 0.1,
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_0",
              route: [
                { x: 0.405, y: 0 },
                { x: 12.4, y: 0 },
              ],
              stroke_width: 0.1,
              port_hints: [],
              color: "#FF0000",
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_0",
              route: [
                { x: -0.405, y: 6.35 },
                { x: -0.405, y: -6.35 },
              ],
              stroke_width: 0.1,
              port_hints: [],
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_1",
              route: [
                { x: -0.405, y: 6.35 },
                { x: 12.295, y: 7.24 },
              ],
              stroke_width: 0.1,
              port_hints: [],
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_2",
              route: [
                { x: 0.405, y: 5.597 },
                { x: 0.405, y: -5.597 },
              ],
              stroke_width: 0.1,
              port_hints: [],
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_3",
              route: [
                { x: 0.405, y: 5.597 },
                { x: 12.295, y: 6.43 },
              ],
              stroke_width: 0.1,
              port_hints: [],
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_4",
              route: [
                { x: 12.295, y: 7.24 },
                { x: 12.295, y: -7.24 },
              ],
              stroke_width: 0.1,
              port_hints: [],
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_5",
              route: [
                { x: 12.295, y: -7.24 },
                { x: -0.405, y: -6.35 },
              ],
              stroke_width: 0.1,
              port_hints: [],
            },
            {
              type: "pcb_fabrication_note_path",
              layer: "top",
              pcb_component_id: "pcb_generic_component_0",
              fabrication_note_path_id: "fabrication_note_path_6",
              route: [
                { x: 12.3, y: -6.43 },
                { x: 0.405, y: -5.597 },
              ],
              stroke_width: 0.1,
              port_hints: [],
            },
            {
              type: "pcb_silkscreen_text",
              layer: "top",
              font: "tscircuit2024",
              font_size: 1,
              pcb_component_id: "pcb_generic_component_0",
              anchor_position: { x: 6.35, y: 0 },
              anchor_alignment: "center",
              text: "${REFERENCE}",
            },
            {
              type: "pcb_fabrication_note_text",
              layer: "top",
              font: "tscircuit2024",
              font_size: 1.27,
              pcb_component_id: "pcb_generic_component_0",
              anchor_position: { x: 6.35, y: 8.5 },
              anchor_alignment: "center",
              text: "REF**",
              port_hints: [],
            },
            {
              type: "pcb_fabrication_note_text",
              layer: "top",
              font: "tscircuit2024",
              font_size: 1.27,
              pcb_component_id: "pcb_generic_component_0",
              anchor_position: { x: 6.35, y: -8.5 },
              anchor_alignment: "center",
              text: "Heatsink_AAVID_576802B03900G",
              port_hints: [],
              color: "#FF0000",
            },
            {
              x: 3,
              y: 3,
              type: "pcb_plated_hole",
              shape: "circular_hole_with_rect_pad",
              layers: ["top", "bottom"],
              port_hints: ["1"],
              pcb_port_id: "pcb_port_100",
              hole_diameter: 1,
              rect_pad_width: 2,
              rect_pad_height: 2,
              pcb_component_id: "pcb_component_100",
              pcb_plated_hole_id: "pcb_plated_hole_100",
            },
            {
              type: "pcb_plated_hole",
              pcb_plated_hole_id: "pcb_plated_hole_1999",
              pcb_component_id: "pcb_component_18",
              pcb_port_id: "pcb_port_37",
              outer_diameter: 2,
              hole_diameter: 1,
              shape: "circle",
              port_hints: ["2"],
              x: -1,
              y: 3,
              layers: ["top", "bottom"],
            },
            {
              type: "pcb_plated_hole",
              pcb_plated_hole_id: "pcb_plated_hole_99",
              pcb_component_id: "pcb_component_58",
              pcb_port_id: "pcb_port_36",
              hole_diameter: 1,
              rect_pad_width: 2,
              rect_pad_height: 2,
              shape: "circular_hole_with_rect_pad",
              port_hints: ["2"],
              x: -4,
              y: 3,
              layers: ["top", "bottom"],
            },

            {
              x: -6.5,
              y: -6.6,
              type: "pcb_plated_hole",
              shape: "pill_hole_with_rect_pad",
              layers: ["top", "bottom"],
              port_hints: ["1"],
              pcb_port_id: "pcb_port_1001",
              hole_height: 2,
              hole_width: 4,
              rect_pad_width: 5,
              rect_pad_height: 3,
              pcb_component_id: "pcb_component_1001",
              pcb_plated_hole_id: "pcb_plated_hole_1001",
            },
            {
              x: 6.5,
              y: -6.5,
              type: "pcb_plated_hole",
              shape: "pill_hole_with_rect_pad",
              layers: ["top", "bottom"],
              port_hints: ["1"],
              pcb_port_id: "pcb_port_1002",
              hole_height: 3,
              hole_width: 2,
              rect_pad_width: 3,
              rect_pad_height: 4,
              pcb_component_id: "pcb_component_1002",
              pcb_plated_hole_id: "pcb_plated_hole_1002",
            },
          ] as any
        }
      />
    </div>
  )
}

export default PlatedHolePillShape
