export default {
  version: "7.1.0",
  settings: {
    alwaysvectorfont: "no",
    verticaltext: "up",
  },
  grid: {
    distance: 0.1,
    unitdist: "inch",
    unit: "inch",
    style: "lines",
    multiple: 1,
    display: "no",
    altdistance: 0.01,
    altunitdist: "inch",
    altunit: "inch",
  },
  layers: [
    {
      number: 1,
      name: "Top",
      color: 4,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 16,
      name: "Bottom",
      color: 1,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 17,
      name: "Pads",
      color: 2,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 18,
      name: "Vias",
      color: 2,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 19,
      name: "Unrouted",
      color: 6,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 20,
      name: "Dimension",
      color: 15,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 21,
      name: "tPlace",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 22,
      name: "bPlace",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 23,
      name: "tOrigins",
      color: 15,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 24,
      name: "bOrigins",
      color: 15,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 25,
      name: "tNames",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 26,
      name: "bNames",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 27,
      name: "tValues",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 28,
      name: "bValues",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 29,
      name: "tStop",
      color: 7,
      fill: 3,
      visible: "yes",
      active: "yes",
    },
    {
      number: 30,
      name: "bStop",
      color: 7,
      fill: 6,
      visible: "no",
      active: "yes",
    },
    {
      number: 31,
      name: "tCream",
      color: 7,
      fill: 4,
      visible: "yes",
      active: "yes",
    },
    {
      number: 32,
      name: "bCream",
      color: 7,
      fill: 5,
      visible: "no",
      active: "yes",
    },
    {
      number: 33,
      name: "tFinish",
      color: 6,
      fill: 3,
      visible: "no",
      active: "yes",
    },
    {
      number: 34,
      name: "bFinish",
      color: 6,
      fill: 6,
      visible: "no",
      active: "yes",
    },
    {
      number: 35,
      name: "tGlue",
      color: 7,
      fill: 4,
      visible: "no",
      active: "yes",
    },
    {
      number: 36,
      name: "bGlue",
      color: 7,
      fill: 5,
      visible: "no",
      active: "yes",
    },
    {
      number: 37,
      name: "tTest",
      color: 7,
      fill: 1,
      visible: "no",
      active: "yes",
    },
    {
      number: 38,
      name: "bTest",
      color: 7,
      fill: 1,
      visible: "no",
      active: "yes",
    },
    {
      number: 39,
      name: "tKeepout",
      color: 4,
      fill: 11,
      visible: "yes",
      active: "yes",
    },
    {
      number: 40,
      name: "bKeepout",
      color: 1,
      fill: 11,
      visible: "yes",
      active: "yes",
    },
    {
      number: 41,
      name: "tRestrict",
      color: 4,
      fill: 10,
      visible: "yes",
      active: "yes",
    },
    {
      number: 42,
      name: "bRestrict",
      color: 1,
      fill: 10,
      visible: "yes",
      active: "yes",
    },
    {
      number: 43,
      name: "vRestrict",
      color: 2,
      fill: 10,
      visible: "yes",
      active: "yes",
    },
    {
      number: 44,
      name: "Drills",
      color: 7,
      fill: 1,
      visible: "no",
      active: "yes",
    },
    {
      number: 45,
      name: "Holes",
      color: 7,
      fill: 1,
      visible: "no",
      active: "yes",
    },
    {
      number: 46,
      name: "Milling",
      color: 3,
      fill: 1,
      visible: "no",
      active: "yes",
    },
    {
      number: 47,
      name: "Measures",
      color: 7,
      fill: 1,
      visible: "no",
      active: "yes",
    },
    {
      number: 48,
      name: "Document",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 49,
      name: "Reference",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 51,
      name: "tDocu",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 52,
      name: "bDocu",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 90,
      name: "Modules",
      color: 5,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 91,
      name: "Nets",
      color: 2,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 92,
      name: "Busses",
      color: 1,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 93,
      name: "Pins",
      color: 2,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 94,
      name: "Symbols",
      color: 4,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 95,
      name: "Names",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 96,
      name: "Values",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 97,
      name: "Info",
      color: 7,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
    {
      number: 98,
      name: "Guide",
      color: 6,
      fill: 1,
      visible: "yes",
      active: "yes",
    },
  ],
  library: {
    packages: [
      {
        circle: [
          {
            x: -4.44,
            y: 4.4,
            radius: 0.1,
            width: 0.2,
            layer: 21,
          },
        ],
        wire: [
          {
            x1: -1.9475,
            y1: 4.425,
            x2: 1.9475,
            y2: 4.425,
            width: 0.127,
            layer: 21,
          },
          {
            x1: -1.9475,
            y1: -4.425,
            x2: 1.9475,
            y2: -4.425,
            width: 0.127,
            layer: 21,
          },
          {
            x1: -3.705,
            y1: 4.5725,
            x2: 3.705,
            y2: 4.5725,
            width: 0.05,
            layer: 39,
          },
          {
            x1: -3.705,
            y1: -4.5725,
            x2: 3.705,
            y2: -4.5725,
            width: 0.05,
            layer: 39,
          },
          {
            x1: -3.705,
            y1: 4.5725,
            x2: -3.705,
            y2: -4.5725,
            width: 0.05,
            layer: 39,
          },
          {
            x1: 3.705,
            y1: 4.5725,
            x2: 3.705,
            y2: -4.5725,
            width: 0.05,
            layer: 39,
          },
        ],
        text: [
          {
            "#text": ">VALUE",
            x: -3.965,
            y: -4.602,
            size: 1.27,
            layer: 27,
            align: "top-left",
          },
          {
            "#text": ">NAME",
            x: -3.965,
            y: 4.602,
            size: 1.27,
            layer: 25,
          },
        ],
        smd: [
          {
            name: 1,
            x: -2.47,
            y: 3.81,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 2,
            x: -2.47,
            y: 2.54,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 3,
            x: -2.47,
            y: 1.27,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 4,
            x: -2.47,
            y: 0,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 5,
            x: -2.47,
            y: -1.27,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 6,
            x: -2.47,
            y: -2.54,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 7,
            x: -2.47,
            y: -3.81,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 8,
            x: 2.47,
            y: -3.81,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 9,
            x: 2.47,
            y: -2.54,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 10,
            x: 2.47,
            y: -1.27,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 11,
            x: 2.47,
            y: 0,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 12,
            x: 2.47,
            y: 1.27,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 13,
            x: 2.47,
            y: 2.54,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
          {
            name: 14,
            x: 2.47,
            y: 3.81,
            dx: 1.97,
            dy: 0.59,
            layer: 1,
            roundness: 25,
          },
        ],
        name: "SOIC127P599X175-14N",
        rect: [],
      },
    ],
    devicesets: [
      {
        description:
          "MCU 8-bit ATtiny AVR CISC 8KB Flash 1.8V/2.5V/3.3V/5V 14-Pin SOIC W Tray",
        gates: [
          {
            name: "G$1",
            symbol: "ATTINY841-SSU",
            x: 0,
            y: 0,
          },
        ],
        devices: [
          {
            connects: [
              {
                gate: "G$1",
                pin: "GND",
                pad: 14,
              },
              {
                gate: "G$1",
                pin: "PA0",
                pad: 13,
              },
              {
                gate: "G$1",
                pin: "PA1",
                pad: 12,
              },
              {
                gate: "G$1",
                pin: "PA2",
                pad: 11,
              },
              {
                gate: "G$1",
                pin: "PA3",
                pad: 10,
              },
              {
                gate: "G$1",
                pin: "PA4",
                pad: 9,
              },
              {
                gate: "G$1",
                pin: "PA5",
                pad: 8,
              },
              {
                gate: "G$1",
                pin: "PA6",
                pad: 7,
              },
              {
                gate: "G$1",
                pin: "PA7",
                pad: 6,
              },
              {
                gate: "G$1",
                pin: "PB0",
                pad: 2,
              },
              {
                gate: "G$1",
                pin: "PB1",
                pad: 3,
              },
              {
                gate: "G$1",
                pin: "PB2",
                pad: 5,
              },
              {
                gate: "G$1",
                pin: "PB3",
                pad: 4,
              },
              {
                gate: "G$1",
                pin: "VCC",
                pad: 1,
              },
            ],
            name: "",
            package: "SOIC127P599X175-14N",
          },
        ],
        name: "ATTINY841-SSU",
        prefix: "U",
      },
    ],
    symbols: [
      {
        wire: [
          {
            x1: 10.16,
            y1: 15.24,
            x2: 10.16,
            y2: -17.78,
            width: 0.1524,
            layer: 94,
          },
          {
            x1: 10.16,
            y1: -17.78,
            x2: -10.16,
            y2: -17.78,
            width: 0.1524,
            layer: 94,
          },
          {
            x1: -10.16,
            y1: -17.78,
            x2: -10.16,
            y2: 15.24,
            width: 0.1524,
            layer: 94,
          },
          {
            x1: -10.16,
            y1: 15.24,
            x2: 10.16,
            y2: 15.24,
            width: 0.1524,
            layer: 94,
          },
        ],
        text: [
          {
            "#text": ">NAME",
            x: -10.16,
            y: 16.002,
            size: 1.778,
            layer: 95,
          },
          {
            "#text": ">VALUE",
            x: -10.16,
            y: -20.32,
            size: 1.778,
            layer: 96,
          },
        ],
        pin: [
          {
            name: "VCC",
            x: 15.24,
            y: 12.7,
            length: "middle",
            direction: "pwr",
            rot: "R180",
          },
          {
            name: "PB0",
            x: 15.24,
            y: 2.54,
            length: "middle",
            rot: "R180",
          },
          {
            name: "PA0",
            x: -15.24,
            y: 7.62,
            length: "middle",
          },
          {
            name: "GND",
            x: 15.24,
            y: -15.24,
            length: "middle",
            direction: "pwr",
            rot: "R180",
          },
          {
            name: "PB1",
            x: 15.24,
            y: 0,
            length: "middle",
            rot: "R180",
          },
          {
            name: "PB2",
            x: 15.24,
            y: -2.54,
            length: "middle",
            rot: "R180",
          },
          {
            name: "PB3",
            x: 15.24,
            y: -5.08,
            length: "middle",
            rot: "R180",
          },
          {
            name: "PA6",
            x: -15.24,
            y: -7.62,
            length: "middle",
          },
          {
            name: "PA7",
            x: -15.24,
            y: -10.16,
            length: "middle",
          },
          {
            name: "PA1",
            x: -15.24,
            y: 5.08,
            length: "middle",
          },
          {
            name: "PA2",
            x: -15.24,
            y: 2.54,
            length: "middle",
          },
          {
            name: "PA3",
            x: -15.24,
            y: 0,
            length: "middle",
          },
          {
            name: "PA4",
            x: -15.24,
            y: -2.54,
            length: "middle",
          },
          {
            name: "PA5",
            x: -15.24,
            y: -5.08,
            length: "middle",
          },
        ],
        name: "ATTINY841-SSU",
      },
    ],
  },
}
